### ISSUE TITLE
fork-network set-validators crashes

### ISSUE THREAD

**Issue by vlad-kopcil** [near/nearcore#10165]
**Describe the bug**
```
module.validator_zero.google_compute_instance.node (remote-exec): 2023-11-14T08:54:34.867042Z ERROR runtime: Failed to check if a state snapshot exists err=STATE_SNAPSHOT_KEY
module.validator_zero.google_compute_instance.node (remote-exec): thread 'main' panicked at tools/fork-network/src/cli.rs:712:14:
module.validator_zero.google_compute_instance.node (remote-exec): Failed to read validators JSON ***validators_path:?***: Error("invalid number", line: 1, column: 62)
module.validator_zero.google_compute_instance.node (remote-exec): stack backtrace:
module.validator_zero.google_compute_instance.node (remote-exec):    0: rust_begin_unwind
module.validator_zero.google_compute_instance.node (remote-exec):              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
module.validator_zero.google_compute_instance.node (remote-exec):    1: core::panicking::panic_fmt
module.validator_zero.google_compute_instance.node (remote-exec):              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
module.validator_zero.google_compute_instance.node (remote-exec):    2: core::result::unwrap_failed
module.validator_zero.google_compute_instance.node (remote-exec):              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
module.validator_zero.google_compute_instance.node (remote-exec):    3: near_fork_network::cli::ForkNetworkCommand::add_validator_accounts
module.validator_zero.google_compute_instance.node (remote-exec):    4: near_fork_network::cli::ForkNetworkCommand::run::***closure***
module.validator_zero.google_compute_instance.node (remote-exec):    5: tokio::task::local::LocalSet::run_until::***closure***
module.validator_zero.google_compute_instance.node (remote-exec):    6: neard::cli::NeardCmd::parse_and_run
module.validator_zero.google_compute_instance.node (remote-exec):    7: neard::main
module.validator_zero.google_compute_instance.node (remote-exec): note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
module.validator_zero.google_compute_instance.node (remote-exec): -bash: line 1:  2988 Aborted                 (core dumped) RUST_LOG=debug ~/neard --unsafe-fast-startup fork-network set-validators --validators /opt/validators.json --epoch-length 1000 --chain-id-suffix "-fork"
```

I wonder if you changed the format of validators.json, would be nice to let me know in such case :)

**To Reproduce**
Run [Create personal forknet](https://github.com/PagodaPlatform/tf-forknet/actions/workflows/create.yml) with default parameters.
This will now use the latest build from branch nikurt-fork-assert in a developer mode, so all build tools are available.

**Expected behavior**
The pipeline should work fine.

**Version (please complete the following information):**
- nearcore https://buildkite.com/nearprotocol/nearcore-release/builds/4196#018bca6f-3d17-4659-abfc-5cd988c3c9a8/103
# ~ubuntu/neard --version
neard (release trunk) (build 1.1.0-4559-g73cc55d10) (rustc 1.73.0) (protocol 64) (db 38)

**Additional context**
I kept my instance `fork-9ad4b179-mainnet-validator-us-central1-01-8411ea9d` running at `130.211.234.174`, feel free to use it for investigation.

Content of /opt/validators.json:
```
[
  {
    "account_id": "fork-9ad4b179-mainnet-validator-01",
    "amount": "50000000000000000000000000000",
    "public_key": "ed25519:64iT93jpv2K7v44DT2y5bkd1NxGZR4vTJc4y8gYNg62b"
  }
]
```

**Comment by nikurt** [comment]
See 
```
"amount": "50000000000000000000000000000",
```

But the struct defines it as numerical field, not as a string:
```
struct Validator {
    amount: Option<Balance>,
}
```

**Comment by vlad-kopcil** [comment]
Well, it's been working this way before.
Also here's an excerpt from random node on mainnet genesis:
```
  "validators": [
    {
      "account_id": "nfvalidator1.near",
      "public_key": "ed25519:14pWWRutZtGFKX4B8q89KVFaUWY1Cqu1JcqYXhCDeFh1",
      "amount": "50000000000000000000000000000"
    },
...
```

also, other amounts are strings, for example
```
  "min_gas_price": "1000000000",
  "max_gas_price": "10000000000000000000000",
```

Why do we need this discrepancy here?
