### ISSUE TITLE
Statelessnet validator crashed because of `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by telezhnaya** [near/nearcore#10660]
```
thread 'actix-rt|system:0|arbiter:347' panicked at /home/olgatelezhnaya/nearcore/core/async/src/messaging.rs:90:63:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
   3: core::ops::function::FnOnce::call_once{{vtable.shim}}
   4: tokio::runtime::task::raw::poll
   5: tokio::task::local::LocalSet::tick
   6: tokio::task::local::LocalSet::run_until::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```
cc @robin-near

**Comment by robin-near** [comment]
Ah oops, I forgot that this would crash nodes for real. @staffik  has a fix for it.

**Comment by telezhnaya** [comment]
@robin-near  I have it again 

```
thread 'actix-rt|system:0|arbiter:494' panicked at /home/olgatelezhnaya/nearcore/core/async/src/messaging.rs:90:63:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
   3: core::ops::function::FnOnce::call_once{{vtable.shim}}
   4: tokio::runtime::task::raw::poll
   5: tokio::task::local::LocalSet::tick
   6: tokio::task::local::LocalSet::run_until::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

**Comment by robin-near** [comment]
Are you sure that node is up to date? messaging.rs doesn't even have an unwrap() call anymore 🤔

**Comment by telezhnaya** [comment]
Yes
`neard (release trunk) (build 1.36.1-214-g92040b372) (rustc 1.76.0) (protocol 82) (db 38)`

Have you updated `statelessnet_latest` branch?

**Comment by telezhnaya** [comment]
https://github.com/near/nearcore/blob/statelessnet_latest/core/async/src/messaging.rs#L90

**Comment by telezhnaya** [comment]
`statelessnet_latest` branch should be updated, we ask all the validators to use it as the source of the latest release
