### ISSUE TITLE
`peer_manager::tests::fuzzers::random_handshake_connect_fuzzer` fails locally

### ISSUE THREAD

**Issue by nagisa** [near/nearcore#10784]
**Describe the bug**

The test fails locally ~every time.

```
test peer_manager::tests::fuzzers::random_handshake_connect_fuzzer has been running for over 60 seconds

--- STDERR:              near-network peer_manager::tests::fuzzers::random_handshake_connect_fuzzer ---
thread 'actix-rt|system:494|arbiter:989' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-rt-2.7.0/src/arbiter.rs:103:18:
Cannot create new Arbiter's Runtime.: Os { code: 24, kind: Uncategorized, message: "Too many open files" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'actix-rt|system:494|arbiter:988' panicked at /home/nagisa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-rt-2.7.0/src/arbiter.rs:156:25:
called `Result::unwrap()` on an `Err` value: RecvError
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: actix_rt::arbiter::Arbiter::new
   4: near_network::peer::peer_actor::PeerActor::spawn
   5: near_network::peer_manager::peer_manager_actor::PeerManagerActor::spawn::{{closure}}::{{closure}}
   6: tokio::runtime::task::core::Core<T,S>::poll
   7: tokio::runtime::task::harness::Harness<T,S>::poll
   8: tokio::task::local::LocalSet::tick
   9: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
  11: tokio::runtime::scheduler::current_thread::Context::enter
  12: tokio::runtime::context::scoped::Scoped<T>::set
  13: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
  14: tokio::runtime::context::runtime::enter_runtime
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**To Reproduce**

`just test`.

**Expected behavior**

Test suite reliably passes.

**Additional context**

This has been happening for quite some time now. I just did not get around to reporting it until now.

**Comment by nagisa** [comment]
cc @Ekleog-NEAR because fuzzers.

**Comment by Ekleog-NEAR** [comment]
This should be fixed by https://github.com/near/nearcore/pull/10818 :)
