### ISSUE TITLE
Near full not not syncing

### ISSUE THREAD

**Issue by Parmanand0712** [near/nearcore#10848]
Near full node was syncing on aws but in morning stopped syncing and now below logs are coming

2024-03-21T06:20:39.014198Z  INFO stats: #115143566 Downloading blocks 0.00% (4801 left; at 115143566) 30 peers ⬇ 4.49 MB/s ⬆ 4.91 MB/s 0.00 bps 0 gas/s CPU: 26%, Mem: 13.5 GB
2024-03-21T06:20:49.016206Z  INFO stats: #115143566 Downloading blocks 0.00% (4808 left; at 115143566) 30 peers ⬇ 4.54 MB/s ⬆ 5.02 MB/s 0.00 bps 0 gas/s CPU: 27%, Mem: 13.5 GB

2024-03-21T06:20:58.129458Z  WARN network: Message dropped because TTL reached 0. msg=RoutedMessageV2 { msg: RoutedMessage { target: PeerId(ed25519:6yac8UUYvoKFDBDymNWZ8ZXSmU2d4C2N5w6uHV7GML37), author: ed25519:mWTfB6NTTCbhuHsWBcE1ckqic9qzS528rn3zb5irhKZ, signature: ed25519:3VSKQWKRV2sYPRMSbET76XwyNhjWgtby5yJmuDJmFgteNMjpiDhhjo5DFVCbZHnRbzw8hFPUqt79DGE5TTEkffig, ttl: 0, body: PartialChunkRequest(ChunkHash(BABZxapKwuYBU7vVeTr3F9zCAmFbNkp7PX6UXLQ5CSEa), [9]) }, created_at: Some(2024-03-21 6:11:09.599815752 +00:00:00), num_hops: Some(0) } from=ed25519:A7mVYCR1DEeS84Vy8gtMdryPzTtUCtEwkJ5Hk6adoqg6

2024-03-21T06:20:59.016940Z  INFO stats: #115143566 Downloading blocks 0.00% (4816 left; at 115143566) 30 peers ⬇ 4.61 MB/s ⬆ 4.96 MB/s 0.00 bps 0 gas/s CPU: 26%, Mem: 13.5 GB

Kindly help me why is it coming and how to solve it.

**Comment by Parmanand0712** [comment]
I am using 1.38.0 but when I am executing ./target/release/neard --home ~/.near run


26-Mar-24e or directory" }
2024-03-26T04:34:37.601232Z  WARN neard: /root/.near/config.json: encountered unrecognised fields: store.state_snapshot_config.compaction_enabled, store.state_snapshot_compaction_enabled
2024-03-26T04:34:37.601242Z  INFO config: Validating Config, extracted from config.json...
2024-03-26T04:34:37.602867Z  INFO near_o11y::reload: Updated the logging layer according to log_config.json
2024-03-26T04:34:37.603830Z  INFO db_opener: Opening NodeStorage path="/root/.near/data" cold_path="none"
2024-03-26T04:34:37.605095Z  INFO db: Opened a new RocksDB instance. num_instances=1
2024-03-26T04:34:46.734529Z  INFO db: Closed a RocksDB instance. num_instances=0
2024-03-26T04:34:46.734556Z  INFO db_opener: The database exists. path=/root/.near/data
2024-03-26T04:34:46.734569Z  INFO db: Opened a new RocksDB instance. num_instances=1
2024-03-26T04:34:57.570872Z  INFO db: Closed a RocksDB instance. num_instances=0
2024-03-26T04:34:57.570914Z  INFO db: Opened a new RocksDB instance. num_instances=1
2024-03-26T04:34:57.602164Z  INFO db: Closed a RocksDB instance. num_instances=0
2024-03-26T04:34:57.602190Z  INFO db: Opened a new RocksDB instance. num_instances=1
2024-03-26T04:34:57.902334Z ERROR runtime: Failed to check if a state snapshot exists err=STATE_SNAPSHOT_KEY
thread 'main' panicked at chain/client/src/client_actor.rs:2070:6:
called Result::unwrap() on an Err value: Chain(DBNotFoundErr("epoch block: EAGw6Ruom5kQanSFu7F2MXCd2N4uskkskYKFWmwGmTJz"))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: nearcore::start_with_config_and_synchronization
   4: neard::cli::RunCmd::run::{{closure}}
   5: tokio::task::local::LocalSet::run_until::{{closure}}
   6: neard::cli::NeardCmd::parse_and_run
   7: neard::main
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.
Aborted (core dumped)

**Comment by telezhnaya** [comment]
Closing due to no response. Please reopen if needed.
