### ISSUE TITLE
test_client_with_multi_test_loop fails with enabled GC

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#11605]
Starts to happen since #11599 if I enable garbage collection. I think it has something to do with shuffling shard assignments, because `ReceiptIdToShardId` is populated based on shard tracking.
The failure happens consistently with the following error:

```
UpdateRefcount: col: ReceiptIdToShardId, key: [1, 184, 74, 161, 214, 77, 205, 161, 15, 136, 147, 150, 101, 117, 132, 31, 208, 125, 93, 142, 117, 42, 95, 124, 110, 98, 127, 102, 77, 4, 5, 47], value: [255, 255, 255, 255, 255, 255, 255, 255]
thread 'tests::client::features::multinode_test_loop_example::test_client_with_multi_test_loop' panicked at core/store/src/db/testdb.rs:101:25:
Inserting value with non-positive refcount
stack backtrace:
...
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
  16:        0x10361ed28 - <near_store::db::testdb::TestDB as near_store::db::Database>::write::h8bbf45af1bd51d31
                               at /Users/Aleksandr1/code/nearcore/core/store/src/db/testdb.rs:101:25
  17:        0x1034db968 - near_store::StoreUpdate::commit::h130abfaf43ba87ee
                               at /Users/Aleksandr1/code/nearcore/core/store/src/lib.rs:699:9
  18:        0x102a27050 - near_chain::store::ChainStoreUpdate::commit::ha44cdd96612ce097
                               at /Users/Aleksandr1/code/nearcore/chain/chain/src/store/mod.rs:2705:9
  19:        0x102a018b8 - near_chain::garbage_collection::<impl near_chain::store::ChainStore>::clear_data::h11f902008063d16d
                               at /Users/Aleksandr1/code/nearcore/chain/chain/src/garbage_collection.rs:226:13
  20:        0x102468fb8 - near_client::gc_actor::GCActor::clear_data::ha533504870423c85
                               at /Users/Aleksandr1/code/nearcore/chain/client/src/gc_actor.rs:49:20
  21:        0x102469160 - near_client::gc_actor::GCActor::gc::h3988965f6e05e8e0
                               at /Users/Aleksandr1/code/nearcore/chain/client/src/gc_actor.rs:78:29
  22:        0x1023dadf8 - near_client::gc_actor::GCActor::gc::{{closure}}::hbbd37c4835382a4c
                               at /Users/Aleksandr1/code/nearcore/chain/client/src/gc_actor.rs:85:13
  23:        0x1021e5310 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf7c54044295a8c15
```

**Comment by tayfunelmas** [comment]
Asked a question on this in https://near.zulipchat.com/#narrow/stream/295302-general/topic/ReceiptIdToShardId.20mapping.20in.20DB/near/447244848.
