### ISSUE TITLE
Unable to run node services, unable to sync

### ISSUE THREAD

**Issue by YuXiaoCoder** [near/nearcore#12354]
### Contact Details

1026840746@qq.com

### Node type

RPC

### Which network are you running?

mainnet

### What happened?

Unable to run node services, unable to sync

### Version

```shell
aurora-refiner 0.28.2-2.2.1
```

### Relevant log output

```shell
2024-10-31T01:43:24.830032Z  INFO indexer: Load config from /mnt/auroramain/node/near...
2024-10-31T01:43:24.843590Z  WARN neard: /mnt/auroramain/node/near/config.json: encountered unrecognised field: state_sync.?.sync.?.external_storage_fallback_threshold
2024-10-31T01:43:24.843607Z  INFO config: Validating Config, extracted from config.json...
2024-10-31T01:43:24.849762Z  WARN genesis: Skipped genesis validation
2024-10-31T01:43:24.849812Z  INFO config: Validating Genesis config and records. This could take a few minutes...
2024-10-31T01:43:24.850006Z  INFO config: All validations have passed!
2024-10-31T01:43:24.858760Z  INFO db_opener: Opening NodeStorage path="/mnt/auroramain/node/near/data" cold_path="none"
2024-10-31T01:43:24.859324Z  INFO db: Opened a new RocksDB instance. num_instances=1
2024-10-31T01:43:24.915339Z  INFO db: Closed a RocksDB instance. num_instances=0
2024-10-31T01:43:24.915360Z  INFO db_opener: The database exists. path=/mnt/auroramain/node/near/data
2024-10-31T01:43:24.915369Z  INFO db: Opened a new RocksDB instance. num_instances=1
2024-10-31T01:43:25.376571Z  INFO db: Closed a RocksDB instance. num_instances=0
2024-10-31T01:43:25.376614Z  INFO db: Opened a new RocksDB instance. num_instances=1
2024-10-31T01:43:25.407669Z  INFO db: Closed a RocksDB instance. num_instances=0
2024-10-31T01:43:25.407689Z  INFO db: Opened a new RocksDB instance. num_instances=1
2024-10-31T01:43:25.649448Z  INFO runtime: Error when getting the gc stop height. This error may naturally occur after the gc_num_epochs_to_keep config is increased. It should disappear as soon as the node builds up all epochs it wants. Error: DB Not Found Error: epoch block: HRKbCC2Dt4tX7fHApoNnDkAChFYE5kqzWULkejRZZCyg
2024-10-31T01:43:25.664069Z  INFO memtrie: Loading tries to memory for shards []...
2024-10-31T01:43:25.665699Z  INFO memtrie: Memtries loading complete for shards []
2024-10-31T01:43:25.665711Z  INFO chain: Init: header head @ #131590669 7TEa7MedJ7o5vEirfPAzcU5bzCVhpnhwea2gob4fgtyq; block head @ #131432894 HRKbCC2Dt4tX7fHApoNnDkAChFYE5kqzWULkejRZZCyg
thread 'main' panicked at /usr/local/cargo/git/checkouts/nearcore-5bf7818cf2261fd0/971e76d/chain/client/src/client_actor.rs:168:6:
called `Result::unwrap()` on an `Err` value: Chain(DBNotFoundErr("epoch block: HRKbCC2Dt4tX7fHApoNnDkAChFYE5kqzWULkejRZZCyg"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread 'actix-rt|system:0|arbiter:1actix-rt|system:0|arbiter:0' panicked at ' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/time/entry.rs/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/time/entry.rs::568568::99:
:
A Tokio 1.x context was found, but it is being shutdown.A Tokio 1.x context was found, but it is being shutdown.
```

### Node head info

```shell
2024-10-31T01:51:56.743438Z  INFO neard: version="2.2.1" build="unknown" latest_protocol=71
2024-10-31T01:51:56.743637Z  WARN neard: /mnt/auroramain/node/near/config.json: encountered unrecognised field: state_sync.?.sync.?.external_storage_fallback_threshold
2024-10-31T01:51:56.743644Z  INFO config: Validating Config, extracted from config.json...
2024-10-31T01:51:56.745643Z  WARN genesis: Skipped genesis validation
2024-10-31T01:51:56.745655Z  WARN genesis: Skipped genesis validation
2024-10-31T01:51:56.745660Z  INFO config: All validations have passed!
2024-10-31T01:51:56.745723Z  INFO db_opener: Opening NodeStorage path="/mnt/auroramain/node/near/data" cold_path="none"
2024-10-31T01:51:56.745736Z  INFO db: Opened a new RocksDB instance. num_instances=1
2024-10-31T01:51:56.770519Z  INFO db: Closed a RocksDB instance. num_instances=0
2024-10-31T01:51:56.770537Z  INFO db_opener: The database exists. path=/mnt/auroramain/node/near/data
2024-10-31T01:51:56.770550Z  INFO db: Opened a new RocksDB instance. num_instances=1
2024-10-31T01:51:56.861987Z  INFO db: Closed a RocksDB instance. num_instances=0
2024-10-31T01:51:56.862020Z  INFO db: Opened a new RocksDB instance. num_instances=1
2024-10-31T01:51:56.883726Z  INFO db: Closed a RocksDB instance. num_instances=0
2024-10-31T01:51:56.883746Z  INFO db: Opened a new RocksDB instance. num_instances=1
"CHUNK_TAIL": 131223643
"FINAL_HEAD": Tip { height: 131432892, last_block_hash: 9sRwBdtfPxUbk46CvYpLPw6ZvqjJLS8Uxnpjsb96HPsR, prev_block_hash: 5Ei6y7b6nec52s1V2rR8ruGUDrQXYLQt2bo3vfLEZieK, epoch_id: EpochId(B69u1PXcKpMWz9ZF5R88Bzts36CiswAGMYM1oG7rbsMk), next_epoch_id: EpochId(7eNGxuudA6PL5WB5jc9vkZWcdmJEftG1Vd2ZLMaajGsn) }
"FORK_TAIL": 131336099
"GENESIS_JSON_HASH": 93on1kcuqTXU94zGyGvBm3YYpPqCkaM8bssbxndgbeRX
"GENESIS_STATE_ROOTS": [8EhZRfDTYujfZoUZtZ3eSMB9gJyFo5zjscR12dEcaxGU]
"HEAD": Tip { height: 131432894, last_block_hash: HRKbCC2Dt4tX7fHApoNnDkAChFYE5kqzWULkejRZZCyg, prev_block_hash: EL8gSixoSmbbdoTGGEGdj8QGhDH4C6KM7EbHoxrRaLzB, epoch_id: EpochId(B69u1PXcKpMWz9ZF5R88Bzts36CiswAGMYM1oG7rbsMk), next_epoch_id: EpochId(7eNGxuudA6PL5WB5jc9vkZWcdmJEftG1Vd2ZLMaajGsn) }
"HEADER_HEAD": Tip { height: 131590669, last_block_hash: 7TEa7MedJ7o5vEirfPAzcU5bzCVhpnhwea2gob4fgtyq, prev_block_hash: EFjaFnUG6xu4U5qQet1herCm9H8wTa558e7Wxoi22hpZ, epoch_id: EpochId(9WSXJ8M5ZPwCZr3sNWeNvh2Bwj3vLDZcVTV15Efpc2bZ), next_epoch_id: EpochId(AvS12NccqdzcZESVaCm7Cr5HpzCjZnbe6Ghy2CZPYsRK) }
"LARGEST_TARGET_HEIGHT": 131433122
"LATEST_KNOWN": LatestKnown { height: 131590669, seen: 1730335140042944331 }
"STATE_SYNC_DUMP:\0\0\0\0\0\0\0\0": AllDumped { epoch_id: EpochId(4c3AEoBnXPoqPM8cQHxqRfXbq5hm6CpJAv9okUSGMMxZ), epoch_height: 2362 }
"STATE_SYNC_DUMP:\u{1}\0\0\0\0\0\0\0": AllDumped { epoch_id: EpochId(4c3AEoBnXPoqPM8cQHxqRfXbq5hm6CpJAv9okUSGMMxZ), epoch_height: 2362 }
"STATE_SYNC_DUMP:\u{2}\0\0\0\0\0\0\0": AllDumped { epoch_id: EpochId(4c3AEoBnXPoqPM8cQHxqRfXbq5hm6CpJAv9okUSGMMxZ), epoch_height: 2362 }
"STATE_SYNC_DUMP:\u{3}\0\0\0\0\0\0\0": AllDumped { epoch_id: EpochId(4c3AEoBnXPoqPM8cQHxqRfXbq5hm6CpJAv9okUSGMMxZ), epoch_height: 2362 }
"SYNC_HEAD": Tip { height: 13740748, last_block_hash: 69A1wh25GwoD2CzEuQhs8D2goWPXqe1Liu3jq1i5tdMS, prev_block_hash: 8ZdbgiXn3JpfGGdMGByMqVE5GppKYrojjHJjgZajNV8Z, epoch_id: EpochId(EeWh36LxiVaZgQRsyCzyAUBhaL5yACKZSjK2vTobAC4d), next_epoch_id: EpochId(7edSVzdsSoo1ujdy79abYv3ztbfx7WDawdhCgKhK5qjj) }
"TAIL": 131336099
2024-10-31T01:51:56.962453Z  INFO db: Closed a RocksDB instance. num_instances=0
```

### Node upgrade history

```shell
time: 2024/09/24 08/28, version: 0.28.2-1.40.0
```

### DB reset history

```shell
The node service has been running normally, yesterday suddenly reported the above error, and then restored by downloading the snapshot, first download the header information, then someone reported this error
```

**Comment by YuXiaoCoder** [comment]
Using the same snapshot, the node version was upgraded to `0.28.2-2.3.0-rc.4`, and it still failed to synchronise the blocks, with the following logs
```log
2024-10-31T03:22:22.623075Z  INFO bandwidth: Bandwidth stats total_bandwidth_used_by_all_peers=176962720 total_msg_received_count=4232
2024-10-31T03:22:24.025494Z  INFO network: Closing connection to Some(ed25519:Bj4Tgq53VfCoG9e7wRUVoHC6tekSh87fWh19NKJxbN6k@35.155.121.62:24567) err=Recv(IO(Kind(UnexpectedEof)))
2024-10-31T03:23:22.623602Z  INFO bandwidth: Bandwidth stats total_bandwidth_used_by_all_peers=180610320 total_msg_received_count=4217
2024-10-31T03:23:38.850228Z  INFO network: Closing connection to Some(ed25519:HVDetoMgi5k7Tx3fGqYpm5WLmiDWZkA6LJajQxXHrEU1@136.243.40.38:24567) err=Recv(IO(Kind(UnexpectedEof)))
2024-10-31T03:24:06.567739Z  INFO network: Closing connection to Some(ed25519:8vgYGwWUbuehP9nwLVrcjBoEzyCQD1Vsc66tSHvsNuXx@64.31.23.98:24567) err=Recv(IO(Kind(UnexpectedEof)))
2024-10-31T03:24:22.624763Z  INFO bandwidth: Bandwidth stats total_bandwidth_used_by_all_peers=197019756 total_msg_received_count=4456
2024-10-31T03:24:24.026959Z  INFO network: Closing connection to Some(ed25519:Bj4Tgq53VfCoG9e7wRUVoHC6tekSh87fWh19NKJxbN6k@35.155.121.62:24567) err=Recv(IO(Kind(UnexpectedEof)))
2024-10-31T03:24:56.312199Z  INFO network: Closing connection to Some(ed25519:6vLH6Tv8xuGz6X5cB7jAKea1oPYbS6koewLt6C2gjpPh@65.108.78.122:24567) err=Recv(IO(Kind(UnexpectedEof)))
2024-10-31T03:25:22.625841Z  INFO bandwidth: Bandwidth stats total_bandwidth_used_by_all_peers=213825630 total_msg_received_count=4500
2024-10-31T03:25:22.931576Z  INFO network: Failed to connect to ed25519:6vLH6Tv8xuGz6X5cB7jAKea1oPYbS6koewLt6C2gjpPh@65.108.78.122:24567 err="PeerActor::spawn(): outbound not allowed: already connected to this peer"
2024-10-31T03:25:32.931503Z  INFO network: Failed to connect to ed25519:6vLH6Tv8xuGz6X5cB7jAKea1oPYbS6koewLt6C2gjpPh@65.108.78.122:24567 err="PeerActor::spawn(): outbound not allowed: already connected to this peer"
2024-10-31T03:25:42.920868Z  INFO network: Failed to connect to ed25519:6vLH6Tv8xuGz6X5cB7jAKea1oPYbS6koewLt6C2gjpPh@65.108.78.122:24567 err="PeerActor::spawn(): outbound not allowed: already connected to this peer"
2024-10-31T03:25:52.916033Z  INFO network: Failed to connect to ed25519:6vLH6Tv8xuGz6X5cB7jAKea1oPYbS6koewLt6C2gjpPh@65.108.78.122:24567 err="PeerActor::spawn(): outbound not allowed: already connected to this peer"
2024-10-31T03:26:02.950219Z  INFO network: Failed to connect to ed25519:6vLH6Tv8xuGz6X5cB7jAKea1oPYbS6koewLt6C2gjpPh@65.108.78.122:24567 err="PeerActor::spawn(): outbound not allowed: already connected to this peer"
2024-10-31T03:26:12.926831Z  INFO network: Failed to connect to ed25519:6vLH6Tv8xuGz6X5cB7jAKea1oPYbS6koewLt6C2gjpPh@65.108.78.122:24567 err="PeerActor::spawn(): outbound not allowed: already connected to this peer"
2024-10-31T03:26:22.626399Z  INFO bandwidth: Bandwidth stats total_bandwidth_used_by_all_peers=249099237 total_msg_received_count=5924
2024-10-31T03:27:22.628350Z  INFO bandwidth: Bandwidth stats total_bandwidth_used_by_all_peers=227431702 total_msg_received_count=5631
2024-10-31T03:27:32.473537Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: H8wEeuPiUNektcpJ4NDhB38Aarq6oVzcPBtb4Ab2h6ZS.
2024-10-31T03:27:37.743297Z  INFO network: Closing connection to Some(ed25519:467hyWrgQNSPHRSZHmJiZj5ykXNCxwvCicnYA9jK2RLu@216.144.245.146:24567) err=Recv(IO(Kind(UnexpectedEof)))
2024-10-31T03:27:42.467066Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: H8wEeuPiUNektcpJ4NDhB38Aarq6oVzcPBtb4Ab2h6ZS.
2024-10-31T03:27:52.467338Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: H8wEeuPiUNektcpJ4NDhB38Aarq6oVzcPBtb4Ab2h6ZS.
2024-10-31T03:28:02.467050Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: H8wEeuPiUNektcpJ4NDhB38Aarq6oVzcPBtb4Ab2h6ZS.
2024-10-31T03:28:12.467973Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: H8wEeuPiUNektcpJ4NDhB38Aarq6oVzcPBtb4Ab2h6ZS.
2024-10-31T03:28:22.468042Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: H8wEeuPiUNektcpJ4NDhB38Aarq6oVzcPBtb4Ab2h6ZS.
2024-10-31T03:28:22.636529Z  INFO bandwidth: Bandwidth stats total_bandwidth_used_by_all_peers=222080917 total_msg_received_count=5531
2024-10-31T03:28:32.467711Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: H8wEeuPiUNektcpJ4NDhB38Aarq6oVzcPBtb4Ab2h6ZS.
2024-10-31T03:28:42.467210Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: H8wEeuPiUNektcpJ4NDhB38Aarq6oVzcPBtb4Ab2h6ZS.
2024-10-31T03:28:52.467504Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: H8wEeuPiUNektcpJ4NDhB38Aarq6oVzcPBtb4Ab2h6ZS.
2024-10-31T03:29:02.467299Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: H8wEeuPiUNektcpJ4NDhB38Aarq6oVzcPBtb4Ab2h6ZS.
```

**Comment by telezhnaya** [comment]
Hey @YuXiaoCoder ,
Could you please download fresh snapshot https://near-nodes.io/validator/compile-and-run-a-node#get-data-backup-1 and use the latest mainnet release? https://github.com/near/nearcore/releases/tag/2.3.0

**Comment by YuXiaoCoder** [comment]
> Hey @YuXiaoCoder , Could you please download fresh snapshot https://near-nodes.io/validator/compile-and-run-a-node#get-data-backup-1 and use the latest mainnet release? https://github.com/near/nearcore/releases/tag/2.3.0

@telezhnaya Can snapshots be synchronised incrementally?

**Comment by telezhnaya** [comment]
Could you please elaborate on this? I don't get the question

**Comment by xinzhongyoumeng** [comment]
> Hey @YuXiaoCoder , Could you please download fresh snapshot https://near-nodes.io/validator/compile-and-run-a-node#get-data-backup-1 and use the latest mainnet release? https://github.com/near/nearcore/releases/tag/2.3.0

hi, @telezhnaya , We meet the same problem, and tried this method(we used the snapshot which is 2024.11.02), the problem is still.

**Comment by xinzhongyoumeng** [comment]
the log is below:
```
2024-11-04T12:03:18.698835Z  INFO runtime: Error when getting the gc stop height. This error may naturally occur after the gc_num_epochs_to_keep config is increased. It should disappear as soon as the node builds up all epochs it wants. Error: DB Not Found Error: epoch block: FqFQz1LfV69NAtESdbd1en1ZFtRsCiFuJyEdWvw8BVpm
2024-11-04T12:03:18.700531Z  INFO memtrie: Loading tries to memory for shards []...
2024-11-04T12:03:18.701070Z  INFO memtrie: Memtries loading complete for shards []
2024-11-04T12:03:18.701079Z  INFO chain: Init: header head @ #131789999 Eu5TryA3nFg9rbJqR1c9BagebWKLFhW6cRdzFStt3BEA; block head @ #131665276 FqFQz1LfV69NAtESdbd1en1ZFtRsCiFuJyEdWvw8BVpm
thread 'main' panicked at /usr/local/cargo/git/checkouts/nearcore-5bf7818cf2261fd0/cf41c79/chain/client/src/client_actor.rs:167:6:
called `Result::unwrap()` on an `Err` value: Chain(DBNotFoundErr("epoch block: FqFQz1LfV69NAtESdbd1en1ZFtRsCiFuJyEdWvw8BVpm"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'actix-rt|system:0|arbiter:0' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/time/entry.rs:568:9:
A Tokio 1.x context was found, but it is being shutdown.
thread 'actix-rt|system:0|arbiter:1' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/time/entry.rs:568:9:
A Tokio 1.x context was found, but it is being shutdown.
```

**Comment by xinzhongyoumeng** [comment]
> @xinzhongyoumeng mainnet or testnet? What neard version do you use? Could you please provide the config as well?

mainnet
the docker image is : nearaurora/srpc2-refiner:0.28.2-2.3.0 
the binary is: /usr/local/bin/aurora-refiner
the command is below(the 131538598 is the /mnt/auroramain/node/refiner/.REFINER_LAST_BLOCK content.):
```
refiner -c /mnt/auroramain/conf/refiner/refiner.json run --height=131538598
```
the config is below:
```
{
    "refiner": {
        "chain_id": 1313161554,
        "engine_path": "/mnt/auroramain/node/engine",
        "tx_tracker_path": "/mnt/auroramain/node/engine/tx_tracker",
        "engine_account_id": "aurora"
    },
    "input_mode": {
        "Nearcore": {
            "path": "/mnt/auroramain/node/near"
        }
    },
    "output_storage": {
        "path": "/mnt/auroramain/node/refiner",
        "batch_size": 1000
    },
    "socket_server": {
        "path": "/mnt/auroramain/node/refiner.sock"
    }
}
```

**Comment by VanBarbascu** [comment]
Hi, @YuXiaoCoder! I am not familiar with Aurora's `refiner` tool.

Your `config.json` looks ok. Can you try to run just the `neard` binary to see if you encounter the same issue?
``` neard --home /mnt/auroramain/node/near run```

**Comment by xinzhongyoumeng** [comment]
> Hi, @YuXiaoCoder! I am not familiar with Aurora's `refiner` tool.
> 
> Your `config.json` looks ok. Can you try to run just the `neard` binary on a claen snapshot to see if you encounter the same issue? ` neard --home /mnt/auroramain/node/near run`

neard version :2.3.0 
snapshot: 2024.11.05
the logs ：
```
2024-11-05T23:26:59.142986Z  INFO stats: #131974464 Downloading headers 93.79% (4713 left; at 132045670) 34 peers ⬇ 5.41 MB/s ⬆ 3.46 MB/s 0.00 bps 0 gas/s CPU: 108%, Mem: 1.04 GB
2024-11-05T23:27:09.571413Z  INFO stats: #131974464 Downloading headers 95.80% (3187 left; at 132047206) 34 peers ⬇ 5.70 MB/s ⬆ 4.33 MB/s 0.00 bps 0 gas/s CPU: 95%, Mem: 1.05 GB
2024-11-05T23:27:21.810205Z  INFO stats: #131974464 Downloading headers 97.14% (2174 left; at 132048230) 35 peers ⬇ 5.46 MB/s ⬆ 4.04 MB/s 0.00 bps 0 gas/s CPU: 67%, Mem: 1.08 GB
2024-11-05T23:27:32.865827Z  INFO stats: #131974464 Downloading headers 99.15% (647 left; at 132049767) 34 peers ⬇ 5.25 MB/s ⬆ 3.83 MB/s 0.00 bps 0 gas/s CPU: 105%, Mem: 1.03 GB



2024-11-06T00:26:07.734895Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:26:17.728533Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:26:27.728671Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:26:37.728751Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:26:47.728756Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:26:57.729266Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:27:07.728611Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:27:17.729038Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:27:27.728467Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:27:37.729197Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:27:47.728851Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:27:57.728623Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:28:07.728601Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:28:17.728812Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:28:27.729370Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:28:37.729283Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:28:47.728903Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:28:57.728478Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:29:07.729015Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:29:17.728859Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:29:27.728868Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:29:37.729073Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:29:47.728838Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:29:57.728497Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:30:07.728894Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
2024-11-06T00:30:17.728598Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 84mQ5Fi8Lbyu3pA3Wp1t2rpDwswcwqAvaRAruF1nLU6K.
```

**Comment by xinzhongyoumeng** [comment]
if the snapshot is bad?

**Comment by VanBarbascu** [comment]
Judging by the gap in logs between header sync at `2024-11-05T23:27:32.865827Z` and node crashing at `2024-11-06T00:57:00.797900Z`, the node seems to do some garbage collection and then state sync.

```
/opt/nearmain/supervisor/node_command.sh: line 51: 26719 Killed                  ${COMMAND}
[2024-11-06 08:57:09] [node_command.sh] exec command [/opt/nearmain/core/neard --home=/mnt/nearmain/node run]
```
This log teslls me that the process was killed and restarted. This may have corrupted the DB.

Check `sudo dmesg` at the time of reset and you may find the reason why your process was killed.
It could be oom killer. If so, how much memory do you have available on that host?

**Comment by tmeinlschmidt** [comment]
fresh snapshot, 2.5.2, the same
````
2025-04-02T15:07:00.074643Z  WARN garbage collection: Error in gc: GC Error: block on canonical chain shouldn't have refcount 0
2025-04-02T15:35:48.818990Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 8gMp5pmn5b41LdLbvZgwk2ZEsmwp24e5FJUrvAEtFF8B.
2025-04-02T15:35:58.818333Z ERROR metrics: Error when exporting postponed receipts count DB Not Found Error: BLOCK: 8gMp5pmn5b41LdLbvZgwk2ZEsmwp24e5FJUrvAEtFF8B.
````

before I remove all the data and resync, the node died of the same as above
````
called `Result::unwrap()` on an `Err` value: Chain(DBNotFoundErr("epoch block:...
````

**Comment by tmeinlschmidt** [comment]
aaand.. tried to restart the docker, db is corrupted.. nice

````
2025-04-02T20:10:27.675901Z  INFO neard: version="2.5.2" build="unknown" latest_protocol=76
2025-04-02T20:10:27.676282Z  INFO config: Validating Config, extracted from config.json...
2025-04-02T20:10:27.678637Z  WARN genesis: Skipped genesis validation
2025-04-02T20:10:27.678652Z  INFO config: Validating Genesis config and records. This could take a few minutes...
2025-04-02T20:10:27.678822Z  INFO config: All validations have passed!
2025-04-02T20:10:27.678910Z  INFO neard::cli: OK: net.core.rmem_max is set to expected value 8388608
2025-04-02T20:10:27.678928Z  INFO neard::cli: OK: net.core.wmem_max is set to expected value 8388608
2025-04-02T20:10:27.678948Z  INFO neard::cli: OK: net.ipv4.tcp_rmem is set to expected value 4096 87380 8388608
2025-04-02T20:10:27.678963Z  INFO neard::cli: OK: net.ipv4.tcp_wmem is set to expected value 4096 16384 8388608
2025-04-02T20:10:27.678978Z  INFO neard::cli: OK: net.ipv4.tcp_slow_start_after_idle is set to expected value 0
2025-04-02T20:10:27.681056Z  INFO neard: Reset the config "/data/log_config.json" because the config file doesn't exist. err=Os { code: 2, kind: NotFound, message: "No such file or directory" }
2025-04-02T20:10:27.681236Z  INFO config: Validating Config, extracted from config.json...
2025-04-02T20:10:27.681247Z  INFO neard: No validator key /data/validator_key.json.
2025-04-02T20:10:27.681273Z  INFO near_o11y::reload: Updated the logging layer according to `log_config.json`
2025-04-02T20:10:27.681284Z  INFO db_opener: Opening NodeStorage path="/data/hot-data" cold_path="none"
2025-04-02T20:10:27.681299Z  INFO db: Opened a new RocksDB instance. num_instances=1
2025-04-02T20:10:27.720489Z  INFO db: Closed a RocksDB instance. num_instances=0
2025-04-02T20:10:27.720500Z  INFO db_opener: The database exists. path=/data/hot-data
2025-04-02T20:10:27.720505Z  INFO db: Opened a new RocksDB instance. num_instances=1
2025-04-02T20:10:27.981814Z  INFO db: Closed a RocksDB instance. num_instances=0
2025-04-02T20:10:27.981842Z  INFO db: Opened a new RocksDB instance. num_instances=1
2025-04-02T20:10:28.013827Z  INFO db: Closed a RocksDB instance. num_instances=0
2025-04-02T20:10:28.013839Z  INFO db: Opened a new RocksDB instance. num_instances=1
thread 'main' panicked at chain/client/src/client_actor.rs:171:6:
called `Result::unwrap()` on an `Err` value: Chain(DBNotFoundErr("epoch block: AzUZKdr3jhF3zvxvpaYEvDQZWLSzjvb44keFoNoDpj3W"))
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: nearcore::start_with_config_and_synchronization
   4: neard::cli::RunCmd::run::{{closure}}
   5: tokio::task::local::LocalSet::run_until::{{closure}}
   6: neard::cli::NeardCmd::parse_and_run
   7: neard::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
````

**Comment by VanBarbascu** [comment]
The `2.5.x` release included the resharding for shards 2 and 3. This means that the node is expected to load entries for 2 and 3. In this case the node ran out of memory building the state in memory during state sync. Crashes during state sync invalidate the db. The only option here is to restart the node with an empty db (clean `/data` folder) and boot nodes set to trigger epoch sync and state sync.

Keep in mind that if a release contains resharding, the memory requirements for RPC nodes are increased. Read the release notes before upgrading. 

I will close this issue but feel free to reach out again if you have this problem again.
