### ISSUE TITLE
Nightly failure: test::test_highload

### ISSUE THREAD

**Issue by SkidanovAlex** [near/nearcore#2552]
Fails consistently.

Example run:
http://nightly.neartest.com/run/f625606891dec008a572ca61ec37da500c2a95cd_200428_135923

Failure:

```
thread 'test::test_highload' panicked at 'assertion failed: (submitted_num - observed_num).abs() <
    f64::max(submitted_num, observed_num) * 0.2', tests/test_tps_regression.rs:185:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1427
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/liballoc/boxed.rs:1031
  11: near_primitives::test_utils::init_stop_on_panic::{{closure}}::{{closure}}
             at core/primitives/src/test_utils.rs:83
  12: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  13: std::panicking::begin_panic
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panicking.rs:438
  14: test_tps_regression::test::run_multiple_nodes
             at tests/test_tps_regression.rs:185
  15: test_tps_regression::test::test_highload::{{closure}}
             at tests/test_tps_regression.rs:197
  16: testlib::test_helpers::heavy_test
             at ./test-utils/testlib/src/test_helpers.rs:17
  17: test_tps_regression::test::test_highload
             at tests/test_tps_regression.rs:197
  18: test_tps_regression::test::test_highload::{{closure}}
             at tests/test_tps_regression.rs:195
  19: core::ops::function::FnOnce::call_once
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libcore/ops/function.rs:232
  20: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/liballoc/boxed.rs:1017
  21: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panic.rs:318
  22: std::panicking::try::do_call
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panicking.rs:331
  23: std::panicking::try
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panicking.rs:274
  24: std::panic::catch_unwind
             at /rustc/f509b26a7730d721ef87423a72b3fdf8724b4afa/src/libstd/panic.rs:394
  25: test::run_test_in_process
             at src/libtest/lib.rs:542
  26: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:451
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[0m[0m[1m[31merror[0m[1m:[0m test failed, to rerun pass '-p nearcore --test test_tps_regression'
```

**Comment by SkidanovAlex** [comment]
Removing from Avocado. The test was mostly fixed, the remaining issues are not worth keeping the test at this point.

**Comment by chefsale** [comment]
@bowenwang1996 This can be closed?
