### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by i7495** [near/nearcore#3408]
**Describe the bug**
My betanet validator node crashed twice with the latest near version. See the logs below.

**To Reproduce**
Start the node, wait till it crashes.

**Version:**
- nearcore `Version: 1.16.0-beta.1, Build: 4ad5b868-modified, Latest Protocol: 39`
- betanet

**Additional context**
```
Sep 28 22:22:01.592  INFO stats: #15720653 6pAX8vxXts1Y342Ck7uAfudmt517AGoaRnwggDwGYgZe V/61 31/29/40 peers ⬇ 266.6kiB/s ⬆ 408.0kiB/s 0.70 bps 0 gas/s CPU: 119%, Mem: 3.2 GiB
Sep 28 22:22:11.595  INFO stats: #15720663 CqPKBKcHy9kipR8rkjCrf7D3Yeu1F5usnE7zWKKEfKps V/61 31/28/40 peers ⬇ 265.0kiB/s ⬆ 440.0kiB/s 0.80 bps 0 gas/s CPU: 121%, Mem: 3.2 GiB
thread 'actix-rt:worker:4' panicked at 'Cannot spawn an arbiter's thread "actix-rt:worker:230": Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/arbiter.rs:148:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: near_actix_utils::init_stop_on_panic::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  12: rust_begin_unwind
             at src/libstd/panicking.rs:385
  13: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:339
  14: actix_rt::arbiter::Arbiter::new::{{closure}}
  15: actix_rt::arbiter::Arbiter::new
  16: near_network::peer_manager::PeerManagerActor::try_connect_peer
  17: <actix::contextitems::ActorMessageStreamItem<A,M,S> as actix::fut::ActorFuture>::poll
  18: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
  19: tokio::runtime::task::raw::poll
  20: tokio::task::local::LocalSet::tick
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  22: actix_rt::runtime::Runtime::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Non-zero exit code: 1" }', neard/src/../src/main.rs:233:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: near_actix_utils::init_stop_on_panic::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  12: rust_begin_unwind
             at src/libstd/panicking.rs:385
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  15: near::main
  16: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mfornet** [comment]
This is failing because nearcore is unable to bind to a port. There are two potential reasons here:

1. This error may happen if you try to reuse a port that is already being used, i.e. if you start two instances of nearcore simultaneously.

2. Right now, there is one thread and one port being used per active connection, and those are not being pooled, i.e. nearcore tries to bind to a new port each time a new connection is established. However, there is a limit on the maximum number of connection (maximum is 40), and I expect ports of closed connections to become available for future usages. However if your machine has low resources, ports may not be available and you hit the error: "Resource temporarily unavailable".

Can you share the features of your machine/setup?

**Comment by bowenwang1996** [comment]
Are you trying to run two neard's at the same time?

**Comment by i7495** [comment]
I have a systemd service that checks for near process, and if near is not running the script will start it.
So it is possible that the issue related to my setup and somehow two near processes was started at the same time. But it worked well before the 1.16.0-beta.1 version.

> Can you share the features of your machine/setup?

It's 4 cores CPU and 8 GB RAM (+4 GB swap)

**Comment by bowenwang1996** [comment]
Looks like it is outdated and there is no action item. Closing
