### ISSUE TITLE
Bug: Node Crashing on StorageInconsistentState

### ISSUE THREAD

**Issue by joesixpack** [near/nearcore#3409]
Betanet 1.16.0-beta.1.

```
Sep 28 20:22:13.635  INFO telemetry: Telemetry data could not be sent due to: Timeout out while waiting for response
thread 'main' panicked at 'no storage errors: Error { inner:    0: failure::backtrace::Backtrace::new
   1: <neard::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::validate_tx
   2: <near_client::client_actor::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
   3: <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle
   4: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
   5: tokio::runtime::task::raw::poll
   6: tokio::task::local::LocalSet::tick
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: actix_rt::runtime::Runtime::block_on
   9: near::main
  10: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at src/libstd/sys_common/backtrace.rs:130
  11: main
  12: __libc_start_main
  13: _start


Storage Error: StorageInconsistentState("Trie node missing") }', chain/client/src/client.rs:1274:32
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: near_actix_utils::init_stop_on_panic::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  12: rust_begin_unwind
             at src/libstd/panicking.rs:385
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  15: <near_client::client_actor::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
  16: <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle
  17: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
  18: tokio::runtime::task::raw::poll
  19: tokio::task::local::LocalSet::tick
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: actix_rt::runtime::Runtime::block_on
  22: near::main
  23: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 28 20:22:17.390 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:295obUe9VLEQDuWaVgs1NdRiZTMezLLdfGZJCxnepURg@155.138.219.103:24567)
Sep 28 20:22:17.390 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:ESDpgMgTePqhcuA42qnE7hZnjtmvwGvbFFqxfSrr9pLu@45.77.7.228:24567)
Sep 28 20:22:17.391 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:8GhQXNP9NsPBae1kZRQRRXxBDrzrnXPvnwNH6tE5xTNs@165.227.7.155:24567)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Non-zero exit code: 1" }', neard/src/../src/main.rs:233:Sep 28 20:22:17.404  WARN network: Peer stream error: Custom { kind: Other, error: "reactor gone" }
13
stack backtrace:
 Sep 28 20:22:17.404  WARN network: Peer stream error: Custom { kind: Other, error: "reactor gone" }
  0: backtraceSep 28 20:22:17.404  WARN network: Peer stream error: Custom { kind: Other, error: "reactor gone" }
::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: near_actix_utils::init_stop_on_panic::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
  12: rust_begin_unwind
             at src/libstd/panicking.rs:385
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  15: near::main
  16: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at src/libstd/rt.rs:52
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Sep 28 20:22:17.409 ERROR actix_server::accept: No workers
```

**Comment by bowenwang1996** [comment]
@joesixpack can you provide the full log?

**Comment by joesixpack** [comment]
[logs.tar.zip](https://github.com/nearprotocol/nearcore/files/5300121/logs.tar.zip)

**Comment by bowenwang1996** [comment]
It is a known issue that your node may very occasionally crash on state sync. When this happens, simply restarting the node should address the issue. It will be addressed when we rewrite syncing.

**Comment by bowenwang1996** [comment]
Looks like no action items here. Closing
