### ISSUE TITLE
nayduck 42085: lightclnt.py KeyError height_to_hash

### ISSUE THREAD

**Issue by mikhailOK** [near/nearcore#3464]
http://nayduck.eastus.cloudapp.azure.com:3000/#/test/42085
```
Traceback (most recent call last):
  File "tests/sanity/lightclnt.py", line 104, in <module>
    get_up_to(16, 22 + first_epoch_switch_height)
  File "tests/sanity/lightclnt.py", line 95, in get_up_to
    hash_ = height_to_hash[i]
KeyError: 27
```

**Comment by bowenwang1996** [comment]
Obsolete
