### ISSUE TITLE
EVM runner crashed betanet due to exceeding gas limit

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#3796]
On betanet nodes crash with
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: HostError(GasLimitExceeded)', runtime/near-evm-runner/src/runner.rs:579:64
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: near_evm_runner::runner::run_evm
   4: node_runtime::actions::execute_function_call
   5: node_runtime::Runtime::apply_action
   6: node_runtime::Runtime::apply_action_receipt
   7: node_runtime::Runtime::apply::{{closure}}
   8: node_runtime::Runtime::apply
   9: neard::runtime::NightshadeRuntime::process_state_update
  10: <neard::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::apply_transactions_with_optional_storage_proof
  11: near_chain::types::RuntimeAdapter::apply_transactions
  12: near_chain::chain::ChainUpdate::apply_chunks
  13: near_chain::chain::ChainUpdate::process_block
  14: near_chain::chain::Chain::process_block_single
  15: near_client::client_actor::ClientActor::process_block
  16: <near_client::client_actor::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
  17: <actix::address::envelope::SyncEnvelopeProxy<A,M> as actix::address::envelope::EnvelopeProxy>::handle
  18: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
  19: tokio::runtime::task::raw::poll
  20: tokio::task::local::LocalSet::tick
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  22: actix_rt::runtime::Runtime::block_on
  23: near::main
```

**Comment by evgenykuzyakov** [comment]
Seems we're only using `set_gas_left` in the EvmGasCounter, so we can't exceed `max_gas`: https://github.com/near/nearcore/blob/2ab1d88e04758ce754bffd00366b88e5e9dcebf1/runtime/near-evm-runner/src/evm_state.rs#L334-L351

**Comment by evgenykuzyakov** [comment]
Oh, seem the issue is with the maximum limit, not prepaid gas:
```
    /// Exceeded the maximum amount of gas allowed to burn per contract
    GasLimitExceeded,
```

So EVM gas exceeded 200Tgas limit.
