### ISSUE TITLE
test_not_ban_peer_for_invalid_block fails unexpectedly

### ISSUE THREAD

**Issue by frol** [near/nearcore#3898]
@bowenwang1996 It seems that the test is flaky: https://buildkite.com/nearprotocol/nearcore/builds/5427#56fd3878-52ac-4f0b-acec-5fd47cc87a0f

The failure is completely unrelated to the change in the PR #3897

```
---- test_not_ban_peer_for_invalid_block stdout ----
thread 'test_not_ban_peer_for_invalid_block' panicked at 'banning peer ed25519:28GkZ4xZg8n2CttrafkygmfVKeD5WEwWavMTKri2xBgm unexpectedly for BadBlockHeader', chain/client/tests/process_blocks.rs:645:29
thread 'test_not_ban_peer_for_invalid_block' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', chain/client/src/test_utils.rs:429:55
thread 'test_not_ban_peer_for_invalid_block' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Non-zero exit code: 1" }', chain/client/tests/process_blocks.rs:654:6
```

**Comment by bowenwang1996** [comment]
@mikhailOK please take a look
