### ISSUE TITLE
CI test sync_empty_state is flaky / sync_empty_state finishes with exit code 0 with errors

### ISSUE THREAD

**Issue by Kouprin** [near/nearcore#4036]
Running locally, approximately each 10th run `sync_empty_state` prints the following:

 Mar 04 22:07:23.041 ERROR view_client: Cannot retrieve chain head: DB Not Found Error: HEAD 
 Cause: Unknown 
 Mar 04 22:07:23.041 ERROR view_client: Cannot retrieve chain head: DB Not Found Error: HEAD 
 Cause: Unknown 
 Mar 04 22:07:23.042 INFO chain: Init: saved genesis: `8MUmVayECNDMvcxQdB66Ay4aUfS57AsAmfmYQBuTqbRT` / <span class="error">[`JBmasMboEJUSAQq4rhLE5DGag9yxK9CeMYzsjAd1v7PT`, `11111111111111111111111111111111`, `8YijkEqArew3cMs7MoeZbbnqPEP8LbCUN85qVb668V6i`, `95uBRr8aRH8wuqGCNdQ5TEyfkk6MX22U9HHTpQjYVQZi`]</span> 
 Mar 04 22:07:23.043 INFO chain: Init: head @ 0 <span class="error">[8MUmVayECNDMvcxQdB66Ay4aUfS57AsAmfmYQBuTqbRT]</span> 
 Mar 04 22:07:29.927 WARN client: Sync: no peers available, disabling sync 
 Mar 04 22:07:29.928 INFO stats: # 45 6GPbjVUitfpnbrs8Cg5G24YpcjwTgkPV4QK88rj7zpK V/1 0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 4.40 bps 0 gas/s CPU: 0%, Mem: 53.2 MiB 
 Mar 04 22:07:33.046 INFO stats: # 0 Waiting for peers 0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 53.9 MiB 
 Mar 04 22:07:39.929 WARN client: Sync: no peers available, disabling sync 
 Mar 04 22:07:39.932 INFO stats: # 93 HWLLDR5x9BNA5oEqiBzH6yWyDLc61sX9kS3XPgAVdk5v V/1 0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 4.80 bps 0 gas/s CPU: 0%, Mem: 55.3 MiB 
 Mar 04 22:07:43.026 INFO network: Handshake timeout expired for Some(ed25519:FXXrTXiKWpXj1R6r5fBvMLpstd8gPyrBq3qMByqKVzKF@127.0.0.1:58031)
 Mar 04 22:07:43.050 INFO stats: # 0 Waiting for peers 0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 55.9 MiB 
 Mar 04 22:07:44.053 INFO client: Received 112 block headers from ed25519:FXXrTXiKWpXj1R6r5fBvMLpstd8gPyrBq3qMByqKVzKF 
 Mar 04 22:07:44.421 INFO sync: State sync: all shards are done 
 Mar 04 22:07:44.431 WARN network: Peer stream error: Custom 

 { kind: Other, error: "IO driver has terminated" } 

 FIRST STAGE 0
 ...
 SECOND STAGE 0
 SECOND STAGE 0
 SECOND STAGE 0
 SECOND STAGE 0
 SECOND STAGE 0
 SECOND STAGE 0
 SECOND STAGE 0

 Process finished with exit code 0

Expected behavior:

 Mar 04 22:10:45.169 INFO chain: Init: saved genesis: `H4sJ3uexfHccHDZWyw6yBK8AMawkno3NYrJ4PFAw852w` / <span class="error">[`JBmasMboEJUSAQq4rhLE5DGag9yxK9CeMYzsjAd1v7PT`, `11111111111111111111111111111111`, `8YijkEqArew3cMs7MoeZbbnqPEP8LbCUN85qVb668V6i`, `95uBRr8aRH8wuqGCNdQ5TEyfkk6MX22U9HHTpQjYVQZi`]</span> 
 Mar 04 22:10:45.169 INFO stats: Server listening at ed25519:Eo9W44tRMwcYcoua11yM7Xfr1DjgR4EWQFM3RU27MEX8@0.0.0.0:58052
 Mar 04 22:10:45.170 INFO chain: Init: head @ 0 <span class="error">[H4sJ3uexfHccHDZWyw6yBK8AMawkno3NYrJ4PFAw852w]</span> 
 Mar 04 22:10:45.287 INFO client: Received 12 block headers from ed25519:FXXrTXiKWpXj1R6r5fBvMLpstd8gPyrBq3qMByqKVzKF 
 Mar 04 22:10:46.311 INFO client: Sync: synced at 12 <span class="error">[3Q4LTG]</span>, ed25519:FXXrTXiKWpXj1R6r5fBvMLpstd8gPyrBq3qMByqKVzKF, highest height peer: 12 
 FIRST STAGE 0
 ...
 SECOND STAGE 36
 SECOND STAGE 37
 SECOND STAGE 37
 SECOND STAGE 38
 SECOND STAGE 38
 SECOND STAGE 39
 SECOND STAGE 39

 Process finished with exit code 0

There are two possible issues:

1.  How flaky `sync_empty_state` is, and
2.  Why failed test returns exit code 0

Running params: `cargo test --color=always --package neard --test sync_state_nodes sync_empty_state --no-fail-fast – --format=json --exact -Z unstable-options --show-output`

Master commit for repro: 4cfe390fb08cdfe929cefcd6f44e16233aab04c8.

**Comment by Kouprin** [comment]
Got timeout:

```
Mar 04 22:33:26.484 ERROR view_client: Cannot retrieve chain head: DB Not Found Error: HEAD 
 Cause: Unknown    
Mar 04 22:33:26.484 ERROR view_client: Cannot retrieve chain head: DB Not Found Error: HEAD 
 Cause: Unknown    
Mar 04 22:33:26.486  INFO chain: Init: saved genesis: `3y8Q5Vnz8Qg2LdusUfzs4sJJWi45UhgwhGG826VwQM2T` / [`JBmasMboEJUSAQq4rhLE5DGag9yxK9CeMYzsjAd1v7PT`, `11111111111111111111111111111111`, `8YijkEqArew3cMs7MoeZbbnqPEP8LbCUN85qVb668V6i`, `95uBRr8aRH8wuqGCNdQ5TEyfkk6MX22U9HHTpQjYVQZi`]    
Mar 04 22:33:26.487  INFO chain: Init: head @ 0 [3y8Q5Vnz8Qg2LdusUfzs4sJJWi45UhgwhGG826VwQM2T]    
Mar 04 22:33:33.364  WARN client: Sync: no peers available, disabling sync    
Mar 04 22:33:33.365  INFO stats: #      45 2kssfSLpwDVHH9bkM8Ufcw2yoyJmfCeNFbY5uXt5Z6qQ V/1  0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 4.40 bps 0 gas/s CPU: 0%, Mem: 51.5 MiB    
Mar 04 22:33:36.488  INFO stats: #       0 Waiting for peers   0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 52.2 MiB    
Mar 04 22:33:43.367  WARN client: Sync: no peers available, disabling sync    
Mar 04 22:33:43.369  INFO stats: #      93 4mqBUkqteHCyCERkveww4rimbF8nu4nGschg4FH1xf4C V/1  0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 4.80 bps 0 gas/s CPU: 0%, Mem: 53.7 MiB    
Mar 04 22:33:46.468  INFO network: Handshake timeout expired for None
Mar 04 22:33:46.492  INFO stats: #       0 Waiting for peers   0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 54.5 MiB    
Mar 04 22:33:47.447  INFO client: Received 112 block headers from ed25519:FXXrTXiKWpXj1R6r5fBvMLpstd8gPyrBq3qMByqKVzKF    
Mar 04 22:33:53.373  INFO stats: #     141 B5GtTKCS9MKpPiXnLXygpwe4jxzDFcSqrsfgehHafEWT V/1  1/1/40 peers ⬇ 20 B/s ⬆ 1.8kiB/s 4.80 bps 0 gas/s CPU: 30%, Mem: 58.3 MiB    
Mar 04 22:33:56.497  INFO stats: State [0: header][1: header][2: header][3: header]   1/1/40 peers ⬇ 2.3kiB/s ⬆ 20 B/s 0.00 bps 0 gas/s CPU: 34%, Mem: 58.7 MiB    
Mar 04 22:34:03.377  INFO stats: #     189 NJDBupVBWo4Uu1VBWnLd7LAGU59jJZMMThPZshPDJj6 V/1  1/1/40 peers ⬇ 20 B/s ⬆ 3.4kiB/s 4.80 bps 0 gas/s CPU: 32%, Mem: 60.0 MiB    
Mar 04 22:34:06.500  INFO stats: State [0: header][1: header][2: header][3: header]   1/1/40 peers ⬇ 4.0kiB/s ⬆ 20 B/s 0.00 bps 0 gas/s CPU: 32%, Mem: 60.7 MiB    
Mar 04 22:34:13.381  INFO stats: #     238 3pu2o6wfrjtH8goPEgCtHQ2zogzsLmTkCSzBqyXK2M1y V/1  1/1/40 peers ⬇ 20 B/s ⬆ 5.1kiB/s 4.90 bps 0 gas/s CPU: 32%, Mem: 62.9 MiB    
Mar 04 22:34:16.504  INFO stats: State [0: header][1: header][2: header][3: header]   1/1/40 peers ⬇ 5.6kiB/s ⬆ 20 B/s 0.00 bps 0 gas/s CPU: 33%, Mem: 63.6 MiB    
Mar 04 22:34:23.385  INFO stats: #     286 FNdBLTU2KEWGvJVefVKV1pdqXKehvmcMsrjmtGnqCtQN V/1  1/1/40 peers ⬇ 20 B/s ⬆ 6.7kiB/s 4.80 bps 0 gas/s CPU: 32%, Mem: 65.0 MiB    
Mar 04 22:34:26.507  INFO stats: State [0: header][1: header][2: header][3: header]   1/1/40 peers ⬇ 7.2kiB/s ⬆ 20 B/s 0.00 bps 0 gas/s CPU: 31%, Mem: 65.6 MiB    
Mar 04 22:34:33.407  INFO stats: #     335 8gY4ga4JSTZEZhqVfJzrfmCiMpj9tjhh56ScnrkXGSTD V/1  1/1/40 peers ⬇ 20 B/s ⬆ 8.3kiB/s 4.89 bps 0 gas/s CPU: 30%, Mem: 66.7 MiB    
Mar 04 22:34:36.516  INFO stats: State [0: header][1: header][2: header][3: header]   1/1/40 peers ⬇ 8.8kiB/s ⬆ 20 B/s 0.00 bps 0 gas/s CPU: 30%, Mem: 67.4 MiB    
Mar 04 22:34:43.410  INFO stats: #     383 3AfguAzpAzYWhtqrCcEPy7FzQD1E795eaMjLtZ3UsJnb V/1  1/1/40 peers ⬇ 20 B/s ⬆ 10.0kiB/s 4.80 bps 0 gas/s CPU: 30%, Mem: 68.8 MiB    
Mar 04 22:34:46.518  INFO stats: State [0: header][1: header][2: header][3: header]   1/1/40 peers ⬇ 10.5kiB/s ⬆ 20 B/s 0.00 bps 0 gas/s CPU: 29%, Mem: 69.1 MiB    
...
Mar 04 22:42:47.826  WARN sync: State sync didn't download the state for shard 3 in 60 seconds, sending StateRequest again    
Mar 04 22:42:47.826  INFO sync: State sync status: me Some("test2"), sync_hash Brn9droPr97FdyhJ915gaB2iNbQjsPSz1QGmzPs6iQii, phase HEADER requests sent 34885, last target Some(AccountId("test1"))    
Mar 04 22:42:53.716  INFO stats: #    2746 DmYtex1PVc6aVuAwaV2KWeBmnJPky3vB98ng74mXU8mN V/1  1/1/40 peers ⬇ 0 B/s ⬆ 9.7kiB/s 4.80 bps 0 gas/s CPU: 33%, Mem: 156.1 MiB    
Mar 04 22:42:56.781  INFO stats: State [0: header][1: header][2: header][3: header]   1/1/40 peers ⬇ 9.7kiB/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 33%, Mem: 156.7 MiB    
Mar 04 22:43:03.720  INFO stats: #    2794 K4CbEMFqkioX3xSJN9Es5yHNFdNjtcVhNMDDnHqGRB7 V/1  1/1/40 peers ⬇ 0 B/s ⬆ 9.7kiB/s 4.80 bps 0 gas/s CPU: 33%, Mem: 157.6 MiB    
Mar 04 22:43:06.785  INFO stats: State [0: header][1: header][2: header][3: header]   1/1/40 peers ⬇ 9.7kiB/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 33%, Mem: 158.1 MiB    
Mar 04 22:43:13.730  INFO stats: #    2843 788SygziREoe22r9giYh4bBP4rkhi9YRyL8smHHReJgy V/1  1/1/40 peers ⬇ 0 B/s ⬆ 9.7kiB/s 4.90 bps 0 gas/s CPU: 33%, Mem: 159.3 MiB    
Mar 04 22:43:16.787  INFO stats: State [0: header][1: header][2: header][3: header]   1/1/40 peers ⬇ 9.7kiB/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 32%, Mem: 159.6 MiB    
Mar 04 22:43:23.732  INFO stats: #    2891 A5uKSieXZLP1LttWG9Nd6AkzuwFNSTsxVzfVaye6MND5 V/1  1/1/40 peers ⬇ 0 B/s ⬆ 9.7kiB/s 4.80 bps 0 gas/s CPU: 32%, Mem: 161.0 MiB    
Mar 04 22:43:26.790  INFO stats: State [0: header][1: header][2: header][3: header]   1/1/40 peers ⬇ 9.7kiB/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 33%, Mem: 161.6 MiB    
Mar 04 22:43:33.737  INFO stats: #    2939 2NNz2AD4aeLaNsZXMiDfwV6uCJyi2nptEbjxTdtRUJpd V/1  1/1/40 peers ⬇ 0 B/s ⬆ 9.7kiB/s 4.80 bps 0 gas/s CPU: 32%, Mem: 162.5 MiB    
Mar 04 22:43:36.792  INFO stats: State [0: header][1: header][2: header][3: header]   1/1/40 peers ⬇ 9.7kiB/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 32%, Mem: 163.0 MiB    
Mar 04 22:43:43.740  INFO stats: #    2988 2Yjm5LktdRt22dYswGvBpEaw9zxnDgze6gH55YkHVkmB V/1  1/1/40 peers ⬇ 0 B/s ⬆ 9.7kiB/s 4.90 bps 0 gas/s CPU: 32%, Mem: 164.2 MiB    
FIRST STAGE 0
...
SECOND STAGE 0
BBBB Slept 600100; max_wait_ms 600000
...

Process finished with exit code 101
```

**Comment by Kouprin** [comment]
With update
```
                                Ok(Ok(b)) if b.header.height >= 40 => {
                                    println!("SECOND STAGE {} DONE", b.header.height);
                                    System::current().stop()
                                }
```
I got
```
Mar 04 22:46:32.826 ERROR view_client: Cannot retrieve chain head: DB Not Found Error: HEAD 
 Cause: Unknown    
Mar 04 22:46:32.826 ERROR view_client: Cannot retrieve chain head: DB Not Found Error: HEAD 
 Cause: Unknown    
Mar 04 22:46:32.828  INFO chain: Init: saved genesis: `CMBxdcXjZ6GQDsU6RTwQDXmLVjqfCZe3csmJsSejXQEy` / [`JBmasMboEJUSAQq4rhLE5DGag9yxK9CeMYzsjAd1v7PT`, `11111111111111111111111111111111`, `8YijkEqArew3cMs7MoeZbbnqPEP8LbCUN85qVb668V6i`, `95uBRr8aRH8wuqGCNdQ5TEyfkk6MX22U9HHTpQjYVQZi`]    
Mar 04 22:46:32.828  INFO chain: Init: head @ 0 [CMBxdcXjZ6GQDsU6RTwQDXmLVjqfCZe3csmJsSejXQEy]    
Mar 04 22:46:39.729  WARN client: Sync: no peers available, disabling sync    
Mar 04 22:46:39.729  INFO stats: #      45 D4TL7Ph1aY7bnewebTDB9URmAWTFwHLPbumZU8xBn4iG V/1  0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 4.40 bps 0 gas/s CPU: 0%, Mem: 52.2 MiB    
Mar 04 22:46:42.832  INFO stats: #       0 Waiting for peers   0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 52.9 MiB    
Mar 04 22:46:49.733  WARN client: Sync: no peers available, disabling sync    
Mar 04 22:46:49.734  INFO stats: #      93 qqXcKiNiBGrpwWLznH9V1CDjGeBTbTWoH6kqcpx2Xmj V/1  0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 4.80 bps 0 gas/s CPU: 0%, Mem: 54.3 MiB    
Mar 04 22:46:52.809  INFO network: Handshake timeout expired for Some(ed25519:FXXrTXiKWpXj1R6r5fBvMLpstd8gPyrBq3qMByqKVzKF@127.0.0.1:58268)
Mar 04 22:46:52.835  INFO stats: #       0 Waiting for peers   0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 0.00 bps 0 gas/s CPU: 0%, Mem: 55.0 MiB    
Mar 04 22:46:53.736  INFO client: Received 111 block headers from ed25519:FXXrTXiKWpXj1R6r5fBvMLpstd8gPyrBq3qMByqKVzKF    
Mar 04 22:46:54.061  INFO sync: State sync: all shards are done    
FIRST STAGE 0
...
SECOND STAGE 0
SECOND STAGE 100 DONE

Process finished with exit code 0
```

I think this is not expected behavior. Looks like the test is broken.

**Comment by bowenwang1996** [comment]
@Kouprin Just to make sure I understand your concerns, this test should fail but it didn't?

**Comment by Kouprin** [comment]
@bowenwang1996
1. Yes, when test jumps from 0 to 100 instantly;
2. The test is also flaky and sometimes fail with timeout (see comment https://github.com/near/nearcore/issues/4036#issuecomment-790998581).

**Comment by Longarithm** [comment]
(2) repeated here: https://buildkite.com/nearprotocol/nearcore/builds/636#d9a889b6-3d43-4620-9f12-726d2edf3632
The test was passed locally.

Some part of error:
```
...
  | [2021-04-13T13:58:34Z] SECOND STAGE 0
  | [2021-04-13T13:58:34Z] SECOND STAGE 0
  | [2021-04-13T13:58:34Z] SECOND STAGE 0
  | [2021-04-13T13:58:34Z] BBBB Slept 600100; max_wait_ms 600000
  | [2021-04-13T13:58:34Z] thread 'sync_empty_state' panicked at 'Timed out waiting for the condition', chain/network/src/test_utils.rs:167:21
  | [2021-04-13T13:58:34Z] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  | [2021-04-13T13:58:34Z] thread 'sync_empty_state' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Non-zero exit code: 1" }', /var/lib/buildkite-agent/builds/buildkite-i-06307b3fbe0caafe4-1/nearprotocol/nearcore/test-utils/actix-test-utils/src/lib.rs:54:15
...
```
