### ISSUE TITLE
AccountV1 pytest failures

### ISSUE THREAD

**Issue by mikhailOK** [near/nearcore#4044]
Something with json serialization of Account in genesis
```
Traceback (most recent call last):
  File "tests/sanity/garbage_collection.py", line 42, in <module>
    1: consensus_config
  File "lib/cluster.py", line 836, in start_cluster
    client_config_changes)
  File "lib/cluster.py", line 774, in init_cluster
    apply_genesis_changes(node_dir, genesis_config_changes)
  File "lib/cluster.py", line 797, in apply_genesis_changes
    assert change[-2] in cur
AssertionError
```

Failing tests: http://nayduck.eastus.cloudapp.azure.com:3000/#/run/1248
```
pytest --timeout=240 sanity/one_val.py --features nightly_protocol --features nightly_protocol_features
pytest --timeout=240 sanity/block_sync.py --features nightly_protocol --features nightly_protocol_features
pytest --timeout=120 sanity/garbage_collection.py --features nightly_protocol --features nightly_protocol_features
pytest --timeout=300 sanity/gc_after_sync.py --features nightly_protocol --features nightly_protocol_features
pytest --timeout=120 sanity/garbage_collection1.py --features nightly_protocol --features nightly_protocol_features
pytest --timeout=300 sanity/gc_sync_after_sync.py --features nightly_protocol --features nightly_protocol_features
pytest --timeout=300 sanity/gc_sync_after_sync.py swap_nodes --features nightly_protocol --features nightly_protocol_features
pytest --timeout=240 sanity/switch_node_key.py --features nightly_protocol --features nightly_protocol_features
```

**Comment by mikhailOK** [comment]
Seems related to #4045

**Comment by chefsale** [comment]
Reverted the PR, as it caused canary and betanet to go down.

**Comment by mikhailOK** [comment]
http://nayduck.eastus.cloudapp.azure.com:3000/#/run/1364 tests are failing
```
Traceback (most recent call last):
  File "tests/sanity/gc_sync_after_sync.py", line 40, in <module>
    ["num_block_producer_seats_per_shard", [10]]], {1: consensus_config})
  File "lib/cluster.py", line 837, in start_cluster
    client_config_changes)
  File "lib/cluster.py", line 775, in init_cluster
    apply_genesis_changes(node_dir, genesis_config_changes)
  File "lib/cluster.py", line 798, in apply_genesis_changes
    assert change[-2] in cur
AssertionError

```

**Comment by chefsale** [comment]
cc: @bowenwang1996 @EgorKulikov

**Comment by bowenwang1996** [comment]
@utka can we change nayduck to pass whether the test is run with nightly feature as an environment variable? Then in the python test we can do things differently based on whether nightly features are enabled.
