### ISSUE TITLE
Database migration 17 -> 18 failure

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearcore#4057]
On betanet we observed the following
```
2021-03-08 14:23:35.593 INFO tailer - show_logs: 21473|neard|betanet 
Mar 08 14:04:17.448  INFO near: Version: 1.2.0, Build: 1ee021d7, Latest Protocol: 105    
Mar 08 14:04:17.859  INFO near: Opening store database at "/home/ubuntu/.near/betanet/data"    
Mar 08 14:04:18.385  INFO near: Migrate DB from version 16 to 17    
Mar 08 14:04:21.332  INFO near: Migrate DB from version 17 to 18    
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Not all bytes read" }', core/store/src/migrations.rs:559:69 
stack backtrace: 
  0: rust_begin_unwind 
            at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475 
  1: core::panicking::panic_fmt 
            at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85 
  2: core::option::expect_none_failed 
            at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221 
  3: core::result::Result<T,E>::unwrap 
            at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/result.rs:973 
  4: near_store::migrations::migrate_17_to_18::{{closure}} 
            at /var/lib/buildkite-agent/builds/buildkite-i-068dcccb7eab0b579-1/nearprotocol/nearcore-nightly-release/core/store/src/migrations.rs:559 
  5: near_store::migrations::map_col_from_key 
            at /var/lib/buildkite-agent/builds/buildkite-i-068dcccb7eab0b579-1/nearprotocol/nearcore-nightly-release/core/store/src/migrations.rs:322 
  6: near_store::migrations::migrate_17_to_18 
            at /var/lib/buildkite-agent/builds/buildkite-i-068dcccb7eab0b579-1/nearprotocol/nearcore-nightly-release/core/store/src/migrations.rs:556 
  7: neard::apply_store_migrations 
            at /var/lib/buildkite-agent/builds/buildkite-i-068dcccb7eab0b579-1/nearprotocol/nearcore-nightly-release/neard/src/lib.rs:190 
  8: neard::init_and_migrate_store 
            at /var/lib/buildkite-agent/builds/buildkite-i-068dcccb7eab0b579-1/nearprotocol/nearcore-nightly-release/neard/src/lib.rs:215 
  9: neard::start_with_config 
            at /var/lib/buildkite-agent/builds/buildkite-i-068dcccb7eab0b579-1/nearprotocol/nearcore-nightly-release/neard/src/lib.rs:228 
 10: neard::main::{{closure}} 
            at /var/lib/buildkite-agent/builds/buildkite-i-068dcccb7eab0b579-1/nearprotocol/nearcore-nightly-release/neard/src/main.rs:247 
 11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll 
            at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79 
 12: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::{{closure}} 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/task/local.rs:634 
 13: tokio::coop::with_budget::{{closure}} 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:121 
 14: std::thread::local::LocalKey<T>::try_with 
            at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:265 
 15: std::thread::local::LocalKey<T>::with 
            at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:241 
 16: tokio::coop::with_budget 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:114 
 17: tokio::coop::budget 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:98 
 18: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}} 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/task/local.rs:634 
 19: tokio::macros::scoped_tls::ScopedKey<T>::set 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/macros/scoped_tls.rs:61 
 20: tokio::task::local::LocalSet::with 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/task/local.rs:548 
 21: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/task/local.rs:624 
 22: tokio::task::local::LocalSet::run_until::{{closure}} 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/task/local.rs:498 
 23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll 
            at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/mod.rs:79 
 24: <core::pin::Pin<P> as core::future::future::Future>::poll 
            at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/future/future.rs:121 
 25: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}} 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:184 
 26: tokio::coop::with_budget::{{closure}} 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:121 
 27: std::thread::local::LocalKey<T>::try_with 
            at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:265 
 28: std::thread::local::LocalKey<T>::with 
            at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:241 
 29: tokio::coop::with_budget 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:114 
 30: tokio::coop::budget 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/coop.rs:98 
 31: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}} 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:184 
 32: tokio::runtime::basic_scheduler::enter::{{closure}} 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:266 
 33: tokio::macros::scoped_tls::ScopedKey<T>::set 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/macros/scoped_tls.rs:61 
 34: tokio::runtime::basic_scheduler::enter 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:266 
 35: tokio::runtime::basic_scheduler::Inner<P>::block_on 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:176 
 36: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:405 
 37: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/basic_scheduler.rs:136 
 38: tokio::runtime::Runtime::block_on 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/mod.rs:450 
 39: tokio::task::local::LocalSet::block_on 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/task/local.rs:459 
 40: actix_rt::runtime::Runtime::block_on 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.1.0/src/runtime.rs:85 
 41: actix_rt::system::SystemRunner::block_on 
            at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.1.0/src/system.rs:186 
 42: neard::main 
            at /var/lib/buildkite-agent/builds/buildkite-i-068dcccb7eab0b579-1/nearprotocol/nearcore-nightly-release/neard/src/main.rs:246 
 43: core::ops::function::FnOnce::call_once 
            at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227 
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
and the database is copied on betanet-nearup6 under /home/ubuntu/.near/backup-2021-03-08

**Comment by Kouprin** [comment]
@bowenwang1996 is `protocol_feature_rectify_inflation` feature enabled in Betanet? BlockInfos will be different then.

**Comment by bowenwang1996** [comment]
> @bowenwang1996 is protocol_feature_rectify_inflation feature enabled in Betanet? BlockInfos will be different then.

Yes

**Comment by bowenwang1996** [comment]
As suggested in #4065, this is caused not by any bugs in the migration, but rather that on betanet nightly migration is applied and then if there is a change on the stable database version, there may be some inconsistencies.
