### ISSUE TITLE
lightclnt.py is flaky

### ISSUE THREAD

**Issue by mikhailOK** [near/nearcore#4134]
Fails about 1/4 of the time
http://nayduck.eastus.cloudapp.azure.com:3000/#/test/118138
```
Traceback (most recent call last):
  File "tests/sanity/lightclnt.py", line 125, in <module>
    assert res['result'] is None
AssertionError
```

**Comment by mikhailOK** [comment]
Different error: http://nayduck.eastus.cloudapp.azure.com:3000/#/test/116349
```
Traceback (most recent call last):
  File "tests/sanity/lightclnt.py", line 131, in <module>
    res['result']['inner_lite'], first_epoch_switch_height)
AssertionError: ({'height': 29, 'epoch_id': '5CMEitwUi4BCWATMf3gquo8drZQrzGMQmTn8tbBbw9Hw', 'next_epoch_id': '4seAxq5Wr81NuMzQni8y8ysvhXdK3sPr2Z5BpXBVaCFS', 'prev_state_root': 'BLwK2zRihsYVv9Pr1fKm5qGMg2QT7qsd8S6PRpptA4TZ', 'outcome_root': '2DoUX6XsDr5BxRN821ZxTLYYcQBzSSxPMTqMU4TLfu35', 'timestamp': 1615994366939673052, 'timestamp_nanosec': '1615994366939673052', 'next_bp_hash': 'Bdknt1NL8wz2NRKjTdZhhNugxMRWUxsVrYqT2Aw4Fgst', 'block_merkle_root': 'HkKprMd7L2FPCHd7nngDCYtvNEnreonLqysJEeTjohdJ'}, 8)
```

**Comment by bowenwang1996** [comment]
There are a couple existing issues on this:
* https://github.com/near/nearcore/issues/3464
* https://github.com/near/nearcore/issues/3220
Should we close the old ones?

**Comment by bowenwang1996** [comment]
obsolete
