### ISSUE TITLE
Tests fail when running `cargo test` locally

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5208]
When running `cargo test --all-features --all-targets` on localhost. I always get following failures,, even on master branch.

```bash
failures:

---- challenges::test_verify_chunk_invalid_proofs_challenge stdout ----
thread 'challenges::test_verify_chunk_invalid_proofs_challenge' panicked at 'assertion failed: false', chain/chain/src/validate.rs:70:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- challenges::test_verify_chunk_invalid_proofs_challenge_decoded_chunk stdout ----
thread 'challenges::test_verify_chunk_invalid_proofs_challenge_decoded_chunk' panicked at 'assertion failed: false', chain/chain/src/validate.rs:70:9

---- challenges::test_verify_chunk_invalid_state_challenge stdout ----
thread 'challenges::test_verify_chunk_invalid_state_challenge' panicked at 'assertion failed: false', chain/chain/src/chain.rs:3204:25

---- process_blocks::test_bad_chunk_mask stdout ----
thread 'process_blocks::test_bad_chunk_mask' panicked at 'assertion failed: false', /home/pmnoxx/repos/nearcore.master/chain/chain/src/chain.rs:3744:13

---- process_blocks::test_data_reset_before_state_sync stdout ----
thread 'process_blocks::test_data_reset_before_state_sync' panicked at 'assertion failed: response.is_ok()', integration-tests/tests/client/process_blocks.rs:2034:5

---- process_blocks::test_invalid_gas_price stdout ----
thread 'process_blocks::test_invalid_gas_price' panicked at 'assertion failed: false', /home/pmnoxx/repos/nearcore.master/chain/chain/src/chain.rs:3756:13


failures:
    challenges::test_verify_chunk_invalid_proofs_challenge
    challenges::test_verify_chunk_invalid_proofs_challenge_decoded_chunk
    challenges::test_verify_chunk_invalid_state_challenge
    process_blocks::test_bad_chunk_mask
    process_blocks::test_data_reset_before_state_sync
    process_blocks::test_invalid_gas_price

```

**Comment by pmnoxx** [comment]
@bowenwang1996 @mm-near @matklad Any ideas?

**Comment by bowenwang1996** [comment]
There is a known issue that not all features are compatible. See https://github.com/near/nearcore/issues/4351 for more details
