### ISSUE TITLE
random nearlib test failure `test/providers.test.js`

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5263]
I saw a random failure of testlib a compute of times:

```


[2021-11-15T11:39:57Z]   ● Console
--
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.log
  | [2021-11-15T11:39:57Z]       Loaded master account test.near key from /var/lib/buildkite-agent/builds/buildkite-i-0d2bee60449168b2c-1/nearprotocol/nearcore/scripts/../testdir/.near/validator_key.json with public key = ed25519:22skMptHjFWNyuEWY22ftn2AbLPSYpmYwGJRGwpNHbTV
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Object.connect (src/connect.ts:60:29)
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.log
  | [2021-11-15T11:39:57Z]       [Function: startFromVersion]
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Object.<anonymous> (test/account_multisig.test.js:59:13)
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.warn
  | [2021-11-15T11:39:57Z]       Retrying transaction test-1636976369379-789506000000000000000:aFDqKEMPEtakwvGyx4gELhMYzHtLfTHUey7qg7bznrh with new nonce.
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       30 \| export function logWarning(...args: any[]): void {
  | [2021-11-15T11:39:57Z]       31 \|     if (!process.env['NEAR_NO_LOGS']){
  | [2021-11-15T11:39:57Z]     > 32 \|         console.warn(...args);
  | [2021-11-15T11:39:57Z]          \|                 ^
  | [2021-11-15T11:39:57Z]       33 \|     }
  | [2021-11-15T11:39:57Z]       34 \| }
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Object.logWarning (src/utils/errors.ts:32:17)
  | [2021-11-15T11:39:57Z]       at src/account.ts:242:21
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.warn
  | [2021-11-15T11:39:57Z]       Retrying transaction test-1636976369379-789506000000000000000:HpStsAvg8MDUJ9BjejDFD8SeCaRovzVzKKWDDXPq96pY with new nonce.
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       30 \| export function logWarning(...args: any[]): void {
  | [2021-11-15T11:39:57Z]       31 \|     if (!process.env['NEAR_NO_LOGS']){
  | [2021-11-15T11:39:57Z]     > 32 \|         console.warn(...args);
  | [2021-11-15T11:39:57Z]          \|                 ^
  | [2021-11-15T11:39:57Z]       33 \|     }
  | [2021-11-15T11:39:57Z]       34 \| }
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Object.logWarning (src/utils/errors.ts:32:17)
  | [2021-11-15T11:39:57Z]       at src/account.ts:242:21
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.warn
  | [2021-11-15T11:39:57Z]       Retrying transaction test-1636976369379-789506000000000000000:7VxDuXbVAeJaPQnx3u1B4DwJ5ApViBLMS84ozWxNHrC5 with new nonce.
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       30 \| export function logWarning(...args: any[]): void {
  | [2021-11-15T11:39:57Z]       31 \|     if (!process.env['NEAR_NO_LOGS']){
  | [2021-11-15T11:39:57Z]     > 32 \|         console.warn(...args);
  | [2021-11-15T11:39:57Z]          \|                 ^
  | [2021-11-15T11:39:57Z]       33 \|     }
  | [2021-11-15T11:39:57Z]       34 \| }
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Object.logWarning (src/utils/errors.ts:32:17)
  | [2021-11-15T11:39:57Z]       at src/account.ts:242:21
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.warn
  | [2021-11-15T11:39:57Z]       Retrying transaction test-1636976369379-789506000000000000000:J5dvv74rQm2HuW5ra6Rm8LMaRrMqvRPkXKsK2KV9GSxe with new nonce.
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       30 \| export function logWarning(...args: any[]): void {
  | [2021-11-15T11:39:57Z]       31 \|     if (!process.env['NEAR_NO_LOGS']){
  | [2021-11-15T11:39:57Z]     > 32 \|         console.warn(...args);
  | [2021-11-15T11:39:57Z]          \|                 ^
  | [2021-11-15T11:39:57Z]       33 \|     }
  | [2021-11-15T11:39:57Z]       34 \| }
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Object.logWarning (src/utils/errors.ts:32:17)
  | [2021-11-15T11:39:57Z]       at src/account.ts:242:21
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.log
  | [2021-11-15T11:39:57Z]       deploying multisig contract for test-1636976369379-789506000000000000000
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Account2FA.deployMultisig (src/account_multisig.ts:232:17)
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.warn
  | [2021-11-15T11:39:57Z]       Retrying transaction test-1636976381362-923683000000000000000:8AMDZXPLQgThoBnQrdc5HsTnnM7i3BkqYTXp9ToHuuJV with new nonce.
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       30 \| export function logWarning(...args: any[]): void {
  | [2021-11-15T11:39:57Z]       31 \|     if (!process.env['NEAR_NO_LOGS']){
  | [2021-11-15T11:39:57Z]     > 32 \|         console.warn(...args);
  | [2021-11-15T11:39:57Z]          \|                 ^
  | [2021-11-15T11:39:57Z]       33 \|     }
  | [2021-11-15T11:39:57Z]       34 \| }
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Object.logWarning (src/utils/errors.ts:32:17)
  | [2021-11-15T11:39:57Z]       at src/account.ts:242:21
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.log
  | [2021-11-15T11:39:57Z]       deploying multisig contract for test-1636976381362-923683000000000000000
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Account2FA.deployMultisig (src/account_multisig.ts:232:17)
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.log
  | [2021-11-15T11:39:57Z]       deploying multisig contract for test-1636976384946-479249000000000000000
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Account2FA.deployMultisig (src/account_multisig.ts:232:17)
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.warn
  | [2021-11-15T11:39:57Z]       Retrying transaction test-1636976384946-479249000000000000000:Bi3i23v251yTfHvWKvyZ53P5NW2MYxTJwBXN8hSx7MTU with new nonce.
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       30 \| export function logWarning(...args: any[]): void {
  | [2021-11-15T11:39:57Z]       31 \|     if (!process.env['NEAR_NO_LOGS']){
  | [2021-11-15T11:39:57Z]     > 32 \|         console.warn(...args);
  | [2021-11-15T11:39:57Z]          \|                 ^
  | [2021-11-15T11:39:57Z]       33 \|     }
  | [2021-11-15T11:39:57Z]       34 \| }
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Object.logWarning (src/utils/errors.ts:32:17)
  | [2021-11-15T11:39:57Z]       at src/account.ts:242:21
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.warn
  | [2021-11-15T11:39:57Z]       Retrying transaction test-1636976390323-569814000000000000000:HCe7cVV5qRgubkkMX6DaqdfnmJ9hMCGkop7SEFiQhvZF with new nonce.
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       30 \| export function logWarning(...args: any[]): void {
  | [2021-11-15T11:39:57Z]       31 \|     if (!process.env['NEAR_NO_LOGS']){
  | [2021-11-15T11:39:57Z]     > 32 \|         console.warn(...args);
  | [2021-11-15T11:39:57Z]          \|                 ^
  | [2021-11-15T11:39:57Z]       33 \|     }
  | [2021-11-15T11:39:57Z]       34 \| }
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Object.logWarning (src/utils/errors.ts:32:17)
  | [2021-11-15T11:39:57Z]       at src/account.ts:242:21
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.log
  | [2021-11-15T11:39:57Z]       deploying multisig contract for test-1636976390323-569814000000000000000
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Account2FA.deployMultisig (src/account_multisig.ts:232:17)
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.log
  | [2021-11-15T11:39:57Z]       deploying multisig contract for test-1636976391978-860094000000000000000
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Account2FA.deployMultisig (src/account_multisig.ts:232:17)
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]     console.warn
  | [2021-11-15T11:39:57Z]       Retrying transaction test-1636976390323-569814000000000000000:56vAc5C3E24oN5MGb8pmS55jJBkAwSkkTr2LrPf6E2Mf with new nonce.
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       30 \| export function logWarning(...args: any[]): void {
  | [2021-11-15T11:39:57Z]       31 \|     if (!process.env['NEAR_NO_LOGS']){
  | [2021-11-15T11:39:57Z]     > 32 \|         console.warn(...args);
  | [2021-11-15T11:39:57Z]          \|                 ^
  | [2021-11-15T11:39:57Z]       33 \|     }
  | [2021-11-15T11:39:57Z]       34 \| }
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:39:57Z]       at Object.logWarning (src/utils/errors.ts:32:17)
  | [2021-11-15T11:39:57Z]       at src/account.ts:242:21
  | [2021-11-15T11:39:57Z]
  | [2021-11-15T11:40:00Z] Mon, 15 Nov 2021 11:40:00 GMT contract.methodName(args, gas, amount) deprecated use `contract.methodName({ args, gas?, amount?, callbackUrl?, meta? })` instead at test/account.test.js:205:24
  | [2021-11-15T11:40:01Z] Nov 15 11:40:01.273  INFO stats: #     197 EhvernuBMkq569GFE8NsGH54FP1Xr2yqpf5RoZjrtWS9 V/1  0/0/40 peers ⬇ 0 B/s ⬆ 0 B/s 4.80 bps 10.40 Tgas/s CPU: 41%, Mem: 217.1 MiB
  | [2021-11-15T11:40:01Z] Mon, 15 Nov 2021 11:40:01 GMT contract.methodName(args, gas, amount) deprecated use `contract.methodName({ args, gas?, amount?, callbackUrl?, meta? })` instead at test/account.test.js:218:31
  | [2021-11-15T11:40:05Z] Mon, 15 Nov 2021 11:40:05 GMT JsonRpcProvider.experimental_protocolConfig() deprecated use `experimental_protocolConfig({ sync_checkpoint: 'genesis' })` to fetch the up-to-date or genesis protocol config explicitly at test/providers.test.js:289:37
  | [2021-11-15T11:40:05Z]  FAIL  test/providers.test.js (41.886 s)
  | [2021-11-15T11:40:05Z]   ● Console


```

https://buildkite.com/nearprotocol/nearcore/builds/6731#a618431e-04dd-4325-ad20-37a793566bd5

```


[2021-11-15T11:40:05Z]
--
  | [2021-11-15T11:40:05Z] Test Suites: 1 failed, 17 passed, 18 total
  | [2021-11-15T11:40:05Z] Tests:       1 failed, 183 passed, 184 total
  | [2021-11-15T11:40:05Z] Snapshots:   0 total
  | [2021-11-15T11:40:05Z] Time:        42.932 s


```

**Comment by pmnoxx** [comment]
@mm-near @bowenwang1996 Any ideas?

**Comment by bowenwang1996** [comment]
Not sure what happened

**Comment by pmnoxx** [comment]
@bowenwang1996 Another failure: https://buildkite.com/nearprotocol/nearcore/builds/9114#2800825f-03a5-4679-b0ba-f24bc1a964cb

```


Fri, 03 Dec 2021 17:27:32 GMT JsonRpcProvider.experimental_protocolConfig() deprecated use `experimental_protocolConfig({ sync_checkpoint: 'genesis' })` to fetch the up-to-date or genesis protocol config explicitly at test/providers.test.js:289:37
--
  | FAIL  test/providers.test.js (40.081 s)
  | ● Console
  |  
  | console.log
  | Loaded master account test.near key from /var/lib/buildkite-agent/builds/buildkite-i-08b2305f496fb5cd2-1/nearprotocol/nearcore/scripts/../testdir/.near/validator_key.json with public key = ed25519:22skMptHjFWNyuEWY22ftn2AbLPSYpmYwGJRGwpNHbTV
  |  
  | at Object.connect (src/connect.ts:60:29)
  |  
  | console.warn
  | Retrying transaction test-1638552418116-269440000000000000000:2ioRk22Zs3q2ocRx2SEUvzHGpujbW1QTh2vDmDSCFLgK with new nonce.
  |  
  | 30 \| export function logWarning(...args: any[]): void {
  | 31 \|     if (!process.env['NEAR_NO_LOGS']){
  | > 32 \|         console.warn(...args);
  | \|                 ^
  | 33 \|     }
  | 34 \| }


```

**Comment by pmnoxx** [comment]
https://buildkite.com/nearprotocol/nearcore/builds/9189#bcf99e40-fbb6-4c19-ac6f-36c711145294

**Comment by pmnoxx** [comment]
https://buildkite.com/nearprotocol/nearcore/builds/9114#2800825f-03a5-4679-b0ba-f24bc1a964cb
