### ISSUE TITLE
Random test failure `sharding_upgrade::test_shard_layout_upgrade_cross_contract_calls`

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5370]
I saw `sharding_upgrade::test_shard_layout_upgrade_cross_contract_calls` fail randomly.

```


---- sharding_upgrade::test_shard_layout_upgrade_cross_contract_calls stdout ----
--
  | [2021-11-18T20:22:46Z] thread 'sharding_upgrade::test_shard_layout_upgrade_cross_contract_calls' panicked at 'assertion failed: `(left != right)`
  | [2021-11-18T20:22:46Z]   left: `9`,
  | [2021-11-18T20:22:46Z]  right: `9`', integration-tests/tests/client/sharding_upgrade.rs:643:13
  | [2021-11-18T20:22:46Z] stack backtrace:
  | [2021-11-18T20:22:46Z]    0: rust_begin_unwind
  | [2021-11-18T20:22:46Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
  | [2021-11-18T20:22:46Z]    1: core::panicking::panic_fmt
  | [2021-11-18T20:22:46Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
  | [2021-11-18T20:22:46Z]    2: core::panicking::assert_failed_inner
  | [2021-11-18T20:22:46Z]    3: core::panicking::assert_failed
  | [2021-11-18T20:22:46Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:140:5
  | [2021-11-18T20:22:46Z]    4: client::sharding_upgrade::test_shard_layout_upgrade_cross_contract_calls
  | [2021-11-18T20:22:46Z]              at ./tests/client/sharding_upgrade.rs:643:13
  | [2021-11-18T20:22:46Z]    5: client::sharding_upgrade::test_shard_layout_upgrade_cross_contract_calls::{{closure}}
  | [2021-11-18T20:22:46Z]              at ./tests/client/sharding_upgrade.rs:622:1
  | [2021-11-18T20:22:46Z]    6: core::ops::function::FnOnce::call_once
  | [2021-11-18T20:22:46Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  | [2021-11-18T20:22:46Z]    7: core::ops::function::FnOnce::call_once
  | [2021-11-18T20:22:46Z]              at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  | [2021-11-18T20:22:46Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  | [2021-11-18T20:22:46Z]
  | [2021-11-18T20:22:46Z]
  | [2021-11-18T20:22:46Z] failures:
  | [2021-11-18T20:22:46Z]     sharding_upgrade::test_shard_layout_upgrade_cross_contract_calls
  | [2021-11-18T20:22:46Z]
  | [2021-11-18T20:22:46Z] test result: FAILED. 89 passed; 1 failed; 6 ignored; 0 measured; 0 filtered out; finished in 62.95s
  | [2021-11-18T20:22:46Z]
  | [2021-11-18T20:22:46Z] error: test failed, to rerun pass '-p integration-tests --test client'

```

https://buildkite.com/nearprotocol/nearcore/builds/7518
 https://buildkite.com/nearprotocol/nearcore/builds/9052#5f85dc86-1aa6-442b-9559-d6447862478d
 https://buildkite.com/nearprotocol/nearcore/builds/9266
https://buildkite.com/nearprotocol/nearcore/builds/9434#a0b21d3e-24b3-406c-bcb1-e70e1db0fd38

I ran this test locally on the same PR once and it worked.

**Comment by pmnoxx** [comment]
@mzhangmzz Any ideas? I see you created  the test. I'll ask this issue to you.

**Comment by pmnoxx** [comment]
Bump https://buildkite.com/nearprotocol/nearcore/builds/9052#5f85dc86-1aa6-442b-9559-d6447862478d

**Comment by pmnoxx** [comment]
Another time https://buildkite.com/nearprotocol/nearcore/builds/9266
I ran it locally `50` times, but I couldn't reproduce it
```
2021-12-06T05:09:29.754335Z  INFO nayduck::cargo_test: run=50 self.cmd.repeat=50 cmd=["cargo", "test", "-p", "integration-tests", "--tests", "test_shard_layout_upgrade_cross_contract_calls"] successes=50 failures=0


```

**Comment by pmnoxx** [comment]
500 times on nayduck  http://nayduck.near.org/#/run/2295

**Comment by pmnoxx** [comment]
I was able to reproduce the issue by running test 300 times in parallel
```
2021-12-06T06:14:33.999043Z  INFO nayduck::cargo_test: self.cmd.repeat=300 cmd=["cargo", "test", "-p", "integration-tests", "--tests", "test_shard_layout_upgrade_cross_contract_calls"] successes=299 failures=1
```

**Comment by bowenwang1996** [comment]
@mzhangmzz please take a look

**Comment by mzhangmzz** [comment]
I'll take a look, sorry that I missed this

**Comment by mzhangmzz** [comment]
solved
