### ISSUE TITLE
Runtime fuzzing is broken

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5386]
This commit https://github.com/near/nearcore/pull/5252/files broke runtime fuzzing

```
+error: internal compiler error: Encountered errors `[FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<&near_primitives_core::types::AccountId as borsh::BorshDeserialize>), []), depth=1),Unimplemented), FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<&network::PeerId as borsh::BorshDeserialize>), []), depth=1),Unimplemented), FulfillmentError(Obligation(predicate=Binder(TraitPredicate(<&types::EpochId as borsh::BorshDeserialize>), []), depth=1),Unimplemented)]` resolving bounds after type-checking
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/codegen.rs:124:24

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1166:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0 (09c42c458 2021-10-18) running on x86_64-apple-darwin

note: compiler flags: -Z sanitizer=address -C opt-level=3 -C embed-bitcode=no -C passes=sancov -C llvm-args=-sanitizer-coverage-level=4 -C llvm-args=-sanitizer-coverage-trace-compares -C llvm-args=-sanitizer-coverage-inline-8bit-counters -C llvm-args=-sanitizer-coverage-pc-table -C link-dead-code -C codegen-units=1 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `near-primitives`

```

See https://github.com/near/nearcore/pull/5385 for Fix

**Comment by pmnoxx** [comment]
The fix works 
```
    Finished release [optimized] target(s) in 0.11s
     Running `target/x86_64-unknown-linux-gnu/release/runtime-fuzzer -artifact_prefix=/home/pmnoxx/repos/nearcore.master/test-utils/runtime-tester/fuzz/artifacts/runtime-fuzzer/ -len_control=0 -prefer_small=0 -max_len=4000000 -rss_limit_mb=10240 /home/pmnoxx/repos/nearcore.master/test-utils/runtime-tester/fuzz/corpus/runtime-fuzzer`
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3979626839
INFO:        0 files found in /home/pmnoxx/repos/nearcore.master/test-utils/runtime-tester/fuzz/corpus/runtime-fuzzer
INFO: A corpus is not provided, starting from an empty corpus
#2      INITED exec/s: 0 rss: 60Mb
ERROR: no interesting inputs were found. Is the code instrumented for coverage? Exiting.

```

@nagisa Can you confirm this works for you as well?
