### ISSUE TITLE
Random test failuire `tests/sanity/db_migration.py`

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5388]
https://buildkite.com/nearprotocol/nearcore/builds/7643#890f7ccf-0837-4703-b901-37cd35bd6282

```


[2021-11-19T18:00:48Z] 2021-11-19 18:00:48,638 Running the current node...
--
  | [2021-11-19T18:00:49Z] Traceback (most recent call last):
  | [2021-11-19T18:00:49Z]   File "tests/sanity/db_migration.py", line 111, in <module>
  | [2021-11-19T18:00:49Z]     main()
  | [2021-11-19T18:00:49Z]   File "tests/sanity/db_migration.py", line 95, in main
  | [2021-11-19T18:00:49Z]     wait_for_blocks_or_timeout(node, 20, 100)
  | [2021-11-19T18:00:49Z]   File "lib/utils.py", line 343, in wait_for_blocks_or_timeout
  | [2021-11-19T18:00:49Z]     status = node.get_status()
  | [2021-11-19T18:00:49Z]   File "lib/cluster.py", line 155, in get_status
  | [2021-11-19T18:00:49Z]     r.raise_for_status()
  | [2021-11-19T18:00:49Z]   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
  | [2021-11-19T18:00:49Z]     raise HTTPError(http_error_msg, response=self)
  | [2021-11-19T18:00:49Z] requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://127.0.0.1:3040/status
  | [2021-11-19T18:00:49Z] [2021-11-19 18:00:49] INFO: Cleaning up node 127.0.0.1:24577 on script exit
  | [2021-11-19T18:00:49Z] [2021-11-19 18:00:49] INFO: Executed store validity tests: 0
  | [2021-11-19T18:00:49Z] 🚨 Error: The command exited with status 1


```

**Comment by pmnoxx** [comment]
@mina86 I see you were editing this test last. Could you take a look?

**Comment by pmnoxx** [comment]
again
https://buildkite.com/nearprotocol/nearcore/builds/8025#e73a9bcc-6b91-4736-85f8-9cf4f99386e2

**Comment by pmnoxx** [comment]
Added a hotfix https://github.com/near/nearcore/pull/5439
