### ISSUE TITLE
Random test failure `routing::max_num_peers_limit`

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5777]
There was one unrelated test failure:

```


test routing::max_num_peers_limit ... FAILED
--
  |  
  | failures:
  |  
  | ---- routing::max_num_peers_limit stdout ----
  | BBBB Slept 15001; max_wait_ms 15000
  | thread 'routing::max_num_peers_limit' panicked at 'Timed out waiting for the condition', chain/network/src/test_utils.rs:123:21
  | stack backtrace:
  | 0: rust_begin_unwind
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
  | 1: core::panicking::panic_fmt
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
  | 2: near_network::test_utils::WaitOrTimeoutActor::wait_or_timeout::{{closure}}
  | at /var/lib/buildkite-agent/builds/buildkite-i-038e98c55d8f9189d-1/nearprotocol/nearcore/chain/network/src/test_utils.rs:123:21
  | 3: <F as actix::utils::TimerFuncBox<A>>::call
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.0-beta.2/src/utils.rs:117:9
  | 4: <actix::utils::TimerFunc<A> as actix::fut::ActorFuture>::poll
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.0-beta.2/src/utils.rs:138:21
  | 5: <core::pin::Pin<P> as actix::fut::ActorFuture>::poll
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.0-beta.2/src/fut/mod.rs:323:9
  | 6: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.11.0-beta.2/src/contextimpl.rs:384:23
  | 7: tokio::runtime::task::core::CoreStage<T>::poll
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/core.rs:151:13
  | 8: tokio::runtime::task::harness::poll_future::{{closure}}
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:461:19
  | 9: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panic/unwind_safe.rs:271:9
  | 10: std::panicking::try::do_call
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  | 11: std::panicking::try
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  | 12: std::panic::catch_unwind
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  | 13: tokio::runtime::task::harness::poll_future
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:449:18
  | 14: tokio::runtime::task::harness::Harness<T,S>::poll_inner
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:98:27
  | 15: tokio::runtime::task::harness::Harness<T,S>::poll
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/harness.rs:53:15
  | 16: tokio::runtime::task::raw::RawTask::poll
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/raw.rs:70:18
  | 17: tokio::runtime::task::LocalNotified<S>::run
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/task/mod.rs:343:9
  | 18: tokio::task::local::LocalSet::tick::{{closure}}
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:521:54
  | 19: tokio::coop::with_budget::{{closure}}
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:106:9
  | 20: std::thread::local::LocalKey<T>::try_with
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:399:16
  | 21: std::thread::local::LocalKey<T>::with
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:375:9
  | 22: tokio::coop::with_budget
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:99:5
  | 23: tokio::coop::budget
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:76:5
  | 24: tokio::task::local::LocalSet::tick
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:521:31
  | 25: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:646:16
  | 26: tokio::macros::scoped_tls::ScopedKey<T>::set
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/macros/scoped_tls.rs:61:9
  | 27: tokio::task::local::LocalSet::with
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:559:9
  | 28: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:632:9
  | 29: tokio::task::local::LocalSet::run_until::{{closure}}
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:505:9
  | 30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
  | 31: <core::pin::Pin<P> as core::future::future::Future>::poll
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/future.rs:119:9
  | 32: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:230:62
  | 33: tokio::coop::with_budget::{{closure}}
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:106:9
  | 34: std::thread::local::LocalKey<T>::try_with
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:399:16
  | 35: std::thread::local::LocalKey<T>::with
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/local.rs:375:9
  | 36: tokio::coop::with_budget
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:99:5
  | 37: tokio::coop::budget
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/coop.rs:76:5
  | 38: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:230:39
  | 39: tokio::runtime::basic_scheduler::enter::{{closure}}
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:339:29
  | 40: tokio::macros::scoped_tls::ScopedKey<T>::set
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/macros/scoped_tls.rs:61:9
  | 41: tokio::runtime::basic_scheduler::enter
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:339:5
  | 42: tokio::runtime::basic_scheduler::Inner<P>::block_on
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:218:9
  | 43: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:489:9
  | 44: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/basic_scheduler.rs:178:24
  | 45: tokio::runtime::Runtime::block_on
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/runtime/mod.rs:461:46
  | 46: tokio::task::local::LocalSet::block_on
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.12.0/src/task/local.rs:466:9
  | 47: actix_rt::runtime::Runtime::block_on
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.3.0/src/runtime.rs:80:9
  | 48: actix_rt::system::SystemRunner::run
  | at /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-2.3.0/src/system.rs:167:15
  | 49: near_actix_test_utils::run_actix
  | at /var/lib/buildkite-agent/builds/buildkite-i-038e98c55d8f9189d-1/nearprotocol/nearcore/test-utils/actix-test-utils/src/lib.rs:103:5
  | 50: network::runner::start_test
  | at ./tests/network/runner.rs:707:5
  | 51: network::routing::max_num_peers_limit
  | at ./tests/network/routing.rs:250:5
  | 52: core::ops::function::FnOnce::call_once
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  | thread 'routing::max_num_peers_limit' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Non-zero exit code: 1" }', /var/lib/buildkite-agent/builds/buildkite-i-038e98c55d8f9189d-1/nearprotocol/nearcore/test-utils/actix-test-utils/src/lib.rs:103:15
  | stack backtrace:
  | 0: rust_begin_unwind
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
  | 1: core::panicking::panic_fmt
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
  | 2: core::result::unwrap_failed
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/result.rs:1617:5
  | 3: core::result::Result<T,E>::unwrap
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/result.rs:1299:23
  | 4: near_actix_test_utils::run_actix
  | at /var/lib/buildkite-agent/builds/buildkite-i-038e98c55d8f9189d-1/nearprotocol/nearcore/test-utils/actix-test-utils/src/lib.rs:103:5
  | 5: network::runner::start_test
  | at ./tests/network/runner.rs:707:5
  | 6: network::routing::max_num_peers_limit
  | at ./tests/network/routing.rs:250:5
  | 7: core::ops::function::FnOnce::call_once
  | at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  |  
  |  
  | failures:
  | routing::max_num_peers_limit
  |  
  | test result: FAILED. 29 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 31.64s
  |  
  | error: test failed, to rerun pass '-p integration-tests --test network'
  | 🚨 Error: The command exited with status 101
  | user command error: exit status 101
  | Running global pre-exit hook

```

https://buildkite.com/nearprotocol/nearcore/builds/9858#b0891364-34f4-466b-b1f8-9162b0a6eac2

**Comment by pmnoxx** [comment]
https://buildkite.com/nearprotocol/nearcore/builds/10423#d9a638e0-bc94-4b4f-a183-d2bd4e09ec63
