### ISSUE TITLE
random test failure `tests/sanity/upgradable.py`

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#5821]
```


[2021-12-13 17:16:33] INFO: Starting node 0 as BOOT NODE
--
  | [2021-12-13 17:16:37] INFO: node 0 started
  | [2021-12-13 17:16:37] INFO: Starting node 1 with --boot-nodes=He7QeRuwizNEhBioYG3u4DZ8jWXyETiyNzFD3MkTjDMf@127.0.0.1:24577
  | [2021-12-13 17:16:40] INFO: node 1 started
  | [2021-12-13 17:16:40] INFO: Starting node 2 with --boot-nodes=He7QeRuwizNEhBioYG3u4DZ8jWXyETiyNzFD3MkTjDMf@127.0.0.1:24577
  | [2021-12-13 17:16:44] INFO: node 2 started
  | [2021-12-13 17:16:44] INFO: Starting node 3 with --boot-nodes=He7QeRuwizNEhBioYG3u4DZ8jWXyETiyNzFD3MkTjDMf@127.0.0.1:24577
  | [2021-12-13 17:16:48] INFO: node 3 started
  | Traceback (most recent call last):
  | File "tests/sanity/upgradable.py", line 178, in <module>
  | main()
  | File "tests/sanity/upgradable.py", line 174, in main
  | test_upgrade()
  | File "tests/sanity/upgradable.py", line 168, in test_upgrade
  | nodes[0].get_account(hex_account_id)['result']['amount'])
  | KeyError: 'result'
  | [2021-12-13 17:18:11] INFO: Cleaning up node 127.0.0.1:24580 on script exit
  | [2021-12-13 17:18:11] INFO: Executed store validity tests: 0
  | [2021-12-13 17:18:11] INFO: Cleaning up node 127.0.0.1:24579 on script exit
  | [2021-12-13 17:18:11] INFO: Executed store validity tests: 0
  | [2021-12-13 17:18:11] INFO: Cleaning up node 127.0.0.1:24578 on script exit
  | [2021-12-13 17:18:11] INFO: Executed store validity tests: 0
  | [2021-12-13 17:18:11] INFO: Cleaning up node 127.0.0.1:24577 on script exit
  | [2021-12-13 17:18:11] INFO: Executed store validity tests: 0


```
https://buildkite.com/nearprotocol/nearcore/builds/10034#67ab3cdf-a3d4-4923-82fa-ef0cfb4ea66a

Related PRs
- #5526 
-

**Comment by miraclx** [comment]
Worked after being retried here: https://buildkite.com/nearprotocol/nearcore/builds/10032#ad6ffa7b-18fb-4f89-8dcd-93559f793e41

But not here after 3 retries: https://buildkite.com/nearprotocol/nearcore/builds/10033#427686fa-5dcb-4dbe-9367-2c3a6c18d5b6

**Comment by pmnoxx** [comment]
@miraclx I have a review in queue, that adds logs to debug this issue: https://github.com/near/nearcore/pull/5526

**Comment by pmnoxx** [comment]
```
{'jsonrpc': '2.0', 'error': {'name': 'HANDLER_ERROR', 'cause': {'name': 'UNAVAILABLE_SHARD', 'info': {'requested_shard_id': 0}}, 'code': -32000, 'message': 'Server error', 'data': 'The node does not track the shard ID 0'}, 'id': 'dontcare'}
```
