### ISSUE TITLE
Validator mainnet node restarted with `memory allocation failed` issue

### ISSUE THREAD

**Issue by ok-everstake** [near/nearcore#5931]
**Description**
Validator mainnet node has been restarted two times with `memory allocation failed` issue.
Node memory usage for the past 2 days `avg 5,78 GB & max 7,6 GB`. 64 GB on the server. 

**To Reproduce**
Nothing special

**Expected behavior**
Validator node works fine without unpredictable restarts

**Logs**
Error on the first restart
```
Dec 20 21:27:31.391  INFO stats: #55625082 4CQ95gS4Ru9vZ8JyQR4YHkab26X6cq4gC9UHe5oEa4dT V/59 34/33/40 peers ⬇ 2.3MiB/s ⬆ 2.0MiB/s 0.80 bps 74.19 Tgas/s CPU: 111%, Mem: 6.7 GiB
memory allocation of 3584 bytes failed
```
Error on the second restart
```
Dec 21 12:22:02.268  INFO stats: #55670205 9WvRTCzVpP6n7GxFGVyLZdJN5cJyZGYWwVaNHuK1EMYS V/52 34/30/40 peers ⬇ 828.6kiB/s ⬆ 2.1MiB/s 0.90 bps 72.72 Tgas/s CPU: 47%, Mem: 7.1 GiB
thread '<unnamed>' panicked at 'TODO creating memory cannot fail: Region("System call failed: Cannot allocate memory (os error 12)")', runtime/near-vm-runner/src/wasmer2_runner.rs:56:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dec 21 12:22:04.278 ERROR network: Received error sending message to client: Mailbox has closed for Some(ed25519:Faoro1uDYXH2AFBA1eG4C5pQaLrk4vhWu6KW2pXpnaD8@142.132.143.229:24567)
memory allocation of memory allocation of 34563456 bytes failed
 bytes failed
```

**Version:**
- nearcore 1.23.0
- rustc 1.57.0
- mainnet validator node

**Additional context** 
I wouldn't have even noticed it if we didn't have a trigger on restart. No missed blocks or any other triggered problems.

**Comment by ok-everstake** [comment]
Validator mainnet node has been restarted two more times today (Dec 23).  Available memory on the server - min 56% for the past 2 days.
```
Dec 23 15:13:46.459  INFO stats: #55825362 59GdowyAkXRarsvkXUfUZzJCDc6cA7bLum8ZZ9GspNpy V/63 34/26/40 peers ⬇ 682.8kiB/s ⬆ 1.4MiB/s 0.90 bps 289.36 Tgas/s CPU: 77%, Mem: 7.8 GiB
memory allocation of 897332 bytes failed
```
```
Dec 23 17:32:05.006  INFO stats: #55832121 8GxXvZzu9bB3H2o52xMZ7WTBkokP3egeRJqSLZ3nnZrD V/65 33/27/40 peers ⬇ 2.4MiB/s ⬆ 2.1MiB/s 0.80 bps 213.27 Tgas/s CPU: 88%, Mem: 6.8 GiB
memory allocation of 2528 bytes failed
```

**Comment by bowenwang1996** [comment]
@matklad is it possible that wasmer sometimes tries to allocate a lot of memory? It could have very well been something else though but just want to double check

**Comment by kucharskim** [comment]
This occurs every couple of days on multiple of our nodes:
```
Jan 03 19:54:49 near03 neard[28265]: thread '<unnamed>' panicked at 'TODO creating memory cannot fail: Region("System call failed: Cannot allocate memory (os error 12)")', runtime/near-vm-runner/src/wasmer2_runner.rs:56:14
```

**Comment by kucharskim** [comment]
We are bumping limits up to:
```
$ grep -e ^Limit /etc/systemd/system/neard.service
LimitDATA=32G
LimitRSS=32G
```

**Comment by kucharskim** [comment]
...we were at 20GB before, for 9 months or so.

**Comment by matklad** [comment]
cc @nagisa 

This particular line indeed allocates a sizable chunk of memory -- 64megs. It's always 64 megs though, it's not variable. It's also serviced directly from mmap, bypassing the allocator. *And* we do this for every contract call, which happens rather often.

So, I am not surprised that this is the line that fails under memory exhaustion condition. 

I would be surprised though if this line is to blame for relative memory increase: if we have a leak here, I'd expect it to be a really big problem which we'd notice immediately.

**Comment by nagisa** [comment]
There are situations other than exhaustion of physical memory bytes that could cause any attempt to allocate return an ENOMEM. In particular, the failure modes are (paraphrasing the man pages for `mmap`):

* The process's maximum number of mappings would have been exceeded.  This error can also occur for `munmap`, when unmapping a region in the middle of an existing mapping, since this results in two smaller mappings on either side of the region being unmapped;
* The process's `RLIMIT_DATA` limit, described in `getrlimit(2)`, would have been exceeded.

Here specifically it is important to note that both of these limits pertain to virtual memory rather than resident memory. (As a side note `RLIMIT_RSS` has no effect since Linux 2.4.30). So both of these failure modes are a plausible points of concern. The map count limit in particular is a limit on the number of map regions process can have and can be quite low by default:

```
$ sysctl vm.max_map_count
vm.max_map_count = 65530
```

So it is possible to receive this error after leaking just 250MiB worth of pages or so, which would not necessarily be very apparent using typical monitoring tools.

Now I cannot really tell for sure where we may be hitting these cases: the increase could be extremely quick to the point where none of the usual sampling-based mechanisms would catch the peak; debugging if we hold onto memory maps excessively would require a core dump after a OOM crash.

---

As a quick'n'easy check, is there any chance anybody experiencing this collects virtual memory utilization metrics over time and could share a slice of these metrics around the time of crash here?

As another check, is there any chance anybody experiencing this has coredumps enabled and a coredump of such an occurrence saved? Listing the mapping table for this coredump would be helpful.

**Comment by ok-everstake** [comment]
@nagisa I have some graphs, not sure if this helps. For the last 15 days, falls around the time of crashes/restarts 
Memory utilization % by zabbix vm.memory.utilization
![Screenshot 2022-01-07 at 02 28 03](https://user-images.githubusercontent.com/68015865/148475885-5c87acf5-d76d-4fc8-bf41-233d6e5ca2cc.png)
Node used RAM by prometheus metrics
![Screenshot 2022-01-07 at 02 24 48](https://user-images.githubusercontent.com/68015865/148475952-026be3c6-e015-4763-90e1-209da257c508.png)

I'll increase vm.max_map_count limit for tests

**Comment by bowenwang1996** [comment]
@ok-everstake thanks for the graphs! It seems that your node either did not run out of memory or did so extremely quickly that prometheus is not able to catch it

**Comment by kucharskim** [comment]
We had that on `mainnet` yesterday:
```
Jul 19 13:17:03 near01 neard[431910]: 2022-07-19T13:17:03.924068Z  INFO stats: #70188894 E4Xa2tcnWGFZjmkc53sQ8BFd74SwsdjvLbRaowg1dTa4 Validator | 100 validators 30 peers ⬇ 3.64 MB/s ⬆ 18.9 MB/s 0.70 bps 240 Tgas/s CPU: 167%, Mem: 9.78 GB
Jul 19 13:17:12 near01 neard[431910]: thread '<unnamed>' panicked at 'creating memory must not fail: Region("System call failed: Cannot allocate memory (os error 12)")', runtime/near-vm-runner/src/wasmer2_runner.rs:53:14
Jul 19 13:17:12 near01 neard[431910]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jul 19 13:17:13 near01 systemd[1]: neard.service: Main process exited, code=killed, status=6/ABRT
Jul 19 13:17:13 near01 systemd[1]: neard.service: Failed with result 'signal'.
Jul 19 13:17:18 near01 systemd[1]: neard.service: Scheduled restart job, restart counter is at 2.
Jul 19 13:17:18 near01 systemd[1]: Stopped NEAR daemon.
Jul 19 13:17:18 near01 systemd[1]: Starting NEAR daemon...
...
```

**Comment by kucharskim** [comment]
```
root@near01 ~ # prlimit -p `pgrep -x neard`
RESOURCE   DESCRIPTION                               SOFT        HARD UNITS
AS         address space limit                  unlimited   unlimited bytes
CORE       max core file size                           0   unlimited bytes
CPU        CPU time                             unlimited   unlimited seconds
DATA       max data size                      34359738368 34359738368 bytes
FSIZE      max file size                        unlimited   unlimited bytes
LOCKS      max number of file locks held        unlimited   unlimited locks
MEMLOCK    max locked-in-memory address space       65536       65536 bytes
MSGQUEUE   max bytes in POSIX mqueues              819200      819200 bytes
NICE       max nice prio allowed to raise               0           0 
NOFILE     max number of open files                 50000       50000 files
NPROC      max number of processes                 256754      256754 processes
RSS        max resident set size                unlimited   unlimited bytes
RTPRIO     max real-time priority                       0           0 
RTTIME     timeout for real-time tasks          unlimited   unlimited microsecs
SIGPENDING max number of pending signals           256754      256754 signals
STACK      max stack size                         8388608   unlimited bytes
```

**Comment by kucharskim** [comment]
This was on an RPC / fullnode, not on a validator node:
```
$ curl -s localhost:3030/status | jq -r .validator_account_id
null
```

**Comment by kucharskim** [comment]
I didn't notice what was at the time in near logs, but I see this in `dmesg -T`:
```
[Mon Aug 22 07:16:31 2022] mmap: actix-rt|system (2898): VmData 34575671296 exceed data ulimit 34359738368. Update limits or use boot option ignore_rlimit_data.
```

**Comment by kucharskim** [comment]
Ah, please ignore previous comment, stray `LimitDATA=32G` in systemd unit file. Need to remove it.
