### ISSUE TITLE
Random test failure `tests::test_download_file::test_file_download`

### ISSUE THREAD

**Issue by pmnoxx** [near/nearcore#6108]
We are seeing random tests failures of  `tests::test_download_file::test_file_download`

https://buildkite.com/nearprotocol/nearcore/builds/12173#0c966f8c-aa21-4a4b-8bb1-13469f78cb1d

```
--
  | failures:
  |  
  | ---- tests::test_download_file::test_file_download stdout ----
  | thread 'tests::test_download_file::test_file_download' panicked at 'called `Result::unwrap()` on an `Err` value: HttpError(hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })))', integration-tests/src/tests/test_download_file.rs:35:6
  | stack backtrace:
  | 0: rust_begin_unwind
  | at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
  | 1: core::panicking::panic_fmt
  | at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
  | 2: core::result::unwrap_failed
  | at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
  | 3: core::result::Result<T,E>::unwrap
  | at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1298:23
  | 4: integration_tests::tests::test_download_file::test_file_download
  | at ./src/tests/test_download_file.rs:31:5
  | 5: integration_tests::tests::test_download_file::test_file_download::{{closure}}
  | at ./src/tests/test_download_file.rs:9:1
  | 6: core::ops::function::FnOnce::call_once
  | at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  | 7: core::ops::function::FnOnce::call_once
  | at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  |  
```

**Comment by marcelo-gonzalez** [comment]
ah yea i have a PR for this: https://github.com/near/nearcore/pull/6097
