### ISSUE TITLE
near 1.27.0 mainnet - Receive bad block: Invalid Chunk State

### ISSUE THREAD

**Issue by kucharskim** [near/nearcore#7245]
**Describe the bug**
RPC non-archive node was running for weeks when suddenly it failed with:
```
2022-07-21T09:38:05.268835Z  WARN chain: Failed to validate chunk extra: InvalidStateRoot.
```

**To Reproduce**
I don't know, it was just running. I have 10 identical nodes, and with exactly the same nearcore binary, only one of them failed like that.

**Expected behavior**
It should just work.

**Version (please complete the following information):**
```
neard@near06:~$ ./neard-1.27.0.bin --version
neard (release 1.27.0) (build crates-0.13.0-20-gac2a43e26) (rustc 1.60.0) (protocol 54) (db 31)
```
Runs on `mainnet`

**Additional context**
Logs coming soon...

**Comment by kucharskim** [comment]
Logs, view-state apply-range, nearcore binary at https://generic.mp/r/iiqp-orqf-kbhr-5az2-rmgw-ivpy-jh2i/

**Comment by kucharskim** [comment]
```
% ./neard-1.27.0.bin --color never view-state apply-range --start-index 70319622 --shard-id 1 --verbose-output
2022-07-22T21:44:23.718912Z  INFO neard: version="1.27.0" build="crates-0.13.0-20-gac2a43e26" latest_protocol=54
2022-07-22T21:44:23.723854Z  INFO near: Opening store database at "/data/neard/.near/data"
2022-07-22T21:44:24.824295Z  INFO db: Created a new RocksDB instance. num_instances=1
Applying chunks in the range 70319622..=70319624 for shard_id 1
Printing results including outcomes of applying receipts
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: StorageInconsistentState("Trie node missing")', tools/state-viewer/src/apply_chain_range.rs:291:86
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
## exit code 134
```

**Comment by kucharskim** [comment]
```
% ./neard-1.27.0.bin --color never view-state apply-range --start-index 70319622 --shard-id 3 --verbose-output
2022-07-22T21:44:26.291230Z  INFO neard: version="1.27.0" build="crates-0.13.0-20-gac2a43e26" latest_protocol=54
2022-07-22T21:44:26.295097Z  INFO near: Opening store database at "/data/neard/.near/data"
2022-07-22T21:44:27.399077Z  INFO db: Created a new RocksDB instance. num_instances=1
Applying chunks in the range 70319622..=70319624 for shard_id 3
Printing results including outcomes of applying receipts
block_height: 70319623, block_hash: BH5FyH4cgezhQqEH94HrQKo4j62GF6ZXpMNmtmmsXPQF
chunk_extra: V2(
    ChunkExtraV2 {
        state_root: `8bkZaP41EFtN3GHMURivR2cGgbcAz7cKaWoD21wCNKPv`,
        outcome_root: `AXGZR8U1UgBd3WaPqqHrSr51FADi4e3aTNdZpf5tPCTc`,
        validator_proposals: [],
        gas_used: 5525973266274,
        gas_limit: 1000000000000000,
        balance_burnt: 485642557877400000000,
    },
)
existing_chunk_extra: V2(
    ChunkExtraV2 {
        state_root: `8bkZaP41EFtN3GHMURivR2cGgbcAz7cKaWoD21wCNKPv`,
        outcome_root: `AXGZR8U1UgBd3WaPqqHrSr51FADi4e3aTNdZpf5tPCTc`,
        validator_proposals: [],
        gas_used: 5525973266274,
        gas_limit: 1000000000000000,
        balance_burnt: 485642557877400000000,
    },
)
outcomes: [
    ExecutionOutcomeWithId {
        id: `8kSqhLB4he6Pzxj1HnKxr4d7EdJUgTtryFmvtQvEW6xv`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [
                `APviQUrGJNhyzWMweFHtVeayLUGVs9wQmdxBoMwWN9R3`,
            ],
            burnt_gas: 2428249682298,
            tokens_burnt: 242824968229800000000,
            status: SuccessReceiptId(APviQUrGJNhyzWMweFHtVeayLUGVs9wQmdxBoMwWN9R3),
            metadata: V1,
        },
    },
    ExecutionOutcomeWithId {
        id: `59oEDy6cFYSfkGWQSgUM1MLXKEiLCtoZt2RE3LjNHUrH`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [
                `HryxFZLRDbQqYbJLyUkpRJCrmpT2x59dnGj3HGZKSkX5`,
            ],
            burnt_gas: 2428175896476,
            tokens_burnt: 242817589647600000000,
            status: SuccessReceiptId(HryxFZLRDbQqYbJLyUkpRJCrmpT2x59dnGj3HGZKSkX5),
            metadata: V1,
        },
    },
    ExecutionOutcomeWithId {
        id: `HE1mFC6y9Lh7GPEUrMmA5YTEiWGkZ2pxnVSvTHjLxZuq`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [],
            burnt_gas: 223182562500,
            tokens_burnt: 0,
            status: SuccessValue(``),
            metadata: V2(
                ------------------------------
                Action gas: 0
                ------ Host functions --------
                ------ Actions --------
                ------------------------------
                ,
            ),
        },
    },
    ExecutionOutcomeWithId {
        id: `F3gbK7BYSsrsMS4JyU2gzcvNQ2PsseoD7zUchsxodA4F`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [],
            burnt_gas: 223182562500,
            tokens_burnt: 0,
            status: SuccessValue(``),
            metadata: V2(
                ------------------------------
                Action gas: 0
                ------ Host functions --------
                ------ Actions --------
                ------------------------------
                ,
            ),
        },
    },
    ExecutionOutcomeWithId {
        id: `6FN7fsk1e2Q2RJ5bveX7exb115iyrkwdhFtg41pkFX4G`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [],
            burnt_gas: 223182562500,
            tokens_burnt: 0,
            status: SuccessValue(``),
            metadata: V2(
                ------------------------------
                Action gas: 0
                ------ Host functions --------
                ------ Actions --------
                ------------------------------
                ,
            ),
        },
    },
]
block_height: 70319622, block_hash: Adxb6hwuWymDsGPKRwoBGuQ1LMtCuGP66cq11wwbXN5m
chunk_extra: V2(
    ChunkExtraV2 {
        state_root: `mL1b1vfxmzm4JvxPJtgGNA9eaHvy8yww3vN9qeNraHo`,
        outcome_root: `6sEu1YBbFUKdRMcHqmd2Sv3sfdSe3ypXKkv67YW2U6GY`,
        validator_proposals: [],
        gas_used: 24882839892341,
        gas_limit: 1000000000000000,
        balance_burnt: 2173613102956300000000,
    },
)
existing_chunk_extra: V2(
    ChunkExtraV2 {
        state_root: `mL1b1vfxmzm4JvxPJtgGNA9eaHvy8yww3vN9qeNraHo`,
        outcome_root: `6sEu1YBbFUKdRMcHqmd2Sv3sfdSe3ypXKkv67YW2U6GY`,
        validator_proposals: [],
        gas_used: 24882839892341,
        gas_limit: 1000000000000000,
        balance_burnt: 2173613102956300000000,
    },
)
outcomes: [
    ExecutionOutcomeWithId {
        id: `12WvhERAUfnP6ARnRGoDFhKsxnA8mSmjq6Uob41pdQno`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [
                `Fo1Sv26JMqm82kgRzMZCWoGL8jQsQM9bNkeCrTjdTySW`,
            ],
            burnt_gas: 2428175896476,
            tokens_burnt: 242817589647600000000,
            status: SuccessReceiptId(Fo1Sv26JMqm82kgRzMZCWoGL8jQsQM9bNkeCrTjdTySW),
            metadata: V1,
        },
    },
    ExecutionOutcomeWithId {
        id: `6MTjewqQQ4s89xjzEzmaca3THtdLv9i5r5RujvW2NWxr`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [
                `69zBp34UkCaznSASvFgVUFBLiQk9GaJ8cEbxjS9cMEq`,
            ],
            burnt_gas: 2428182604278,
            tokens_burnt: 242818260427800000000,
            status: SuccessReceiptId(69zBp34UkCaznSASvFgVUFBLiQk9GaJ8cEbxjS9cMEq),
            metadata: V1,
        },
    },
    ExecutionOutcomeWithId {
        id: `8dheqXd3t9A1Don1Hs3NgWjmC9Uw4CjGP8zP162accu5`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [
                `sZzUhaJ5RUQEXNseZFmxhytJNMM8SKvpK696pGvPC9q`,
            ],
            burnt_gas: 2428068571644,
            tokens_burnt: 242806857164400000000,
            status: SuccessReceiptId(sZzUhaJ5RUQEXNseZFmxhytJNMM8SKvpK696pGvPC9q),
            metadata: V1,
        },
    },
    ExecutionOutcomeWithId {
        id: `C4qgfRUWCajwz2QH4ZR1UASb6DjB84zwNxi6oqiz3w5p`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [
                `BAtxvJJHqzXtgFBqawCokKBXCQzBjNmRwfezyrsiEm7U`,
            ],
            burnt_gas: 2428403961744,
            tokens_burnt: 242840396174400000000,
            status: SuccessReceiptId(BAtxvJJHqzXtgFBqawCokKBXCQzBjNmRwfezyrsiEm7U),
            metadata: V1,
        },
    },
    ExecutionOutcomeWithId {
        id: `3h4jsNKYEB16kfd47qfMG9hqrFtyFvzsLye3TvkCRj6s`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [
                `CCqCwXBXefW6kEprA7Zs1Zdi7dz61xNhvBYp895g5mRC`,
            ],
            burnt_gas: 2428323468120,
            tokens_burnt: 242832346812000000000,
            status: SuccessReceiptId(CCqCwXBXefW6kEprA7Zs1Zdi7dz61xNhvBYp895g5mRC),
            metadata: V1,
        },
    },
    ExecutionOutcomeWithId {
        id: `8NGu62zQAQM4zw4tZGJ7PBTTZYkSdnwtXq9aFHJ35shB`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [
                `HE1mFC6y9Lh7GPEUrMmA5YTEiWGkZ2pxnVSvTHjLxZuq`,
            ],
            burnt_gas: 4307081806509,
            tokens_burnt: 430708180650900000000,
            status: SuccessValue(``),
            metadata: V2(
                ------------------------------
                Action gas: 0
                ------ Host functions --------
                base -> 9531651996 [0% host]
                contract_loading_base -> 35445963 [0% host]
                contract_loading_bytes -> 47474969250 [2% host]
                read_memory_base -> 33928221600 [1% host]
                read_memory_byte -> 2276998467 [0% host]
                write_memory_base -> 33645538332 [1% host]
                write_memory_byte -> 2244388128 [0% host]
                read_register_base -> 27688817046 [1% host]
                read_register_byte -> 79638096 [0% host]
                write_register_base -> 34386269832 [1% host]
                write_register_byte -> 3527851392 [0% host]
                storage_write_base -> 192590208000 [10% host]
                storage_write_key_byte -> 1762071675 [0% host]
                storage_write_value_byte -> 11507877969 [0% host]
                storage_write_evicted_byte -> 11915520897 [0% host]
                storage_read_base -> 394497920250 [21% host]
                storage_read_key_byte -> 6283364199 [0% host]
                storage_read_value_byte -> 2261235015 [0% host]
                touching_trie_node -> 595772369262 [32% host]
                read_cached_trie_node -> 405840000000 [22% host]
                ------ Actions --------
                ------------------------------
                ,
            ),
        },
    },
    ExecutionOutcomeWithId {
        id: `6nTq3fAN34fLz6kUV3MEHpDt2QAH4mZrX14wjzc8b5Ng`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [
                `Hjp6TYTs9XQ5eUTUumqSqZ1RTWVu49HptjWM168dLo6R`,
                `AiQWve4FZPJUCPe1ZvSCTBXv48GKdi2eC8WxYjewYWkY`,
            ],
            burnt_gas: 7318690771070,
            tokens_burnt: 731869077107000000000,
            status: SuccessValue(``),
            metadata: V2(
                ------------------------------
                Action gas: 424555062500
                ------ Host functions --------
                base -> 15886086660 [0% host]
                contract_loading_base -> 35445963 [0% host]
                contract_loading_bytes -> 76008372750 [1% host]
                read_memory_base -> 73076169600 [1% host]
                read_memory_byte -> 3554246355 [0% host]
                write_memory_base -> 47664512637 [1% host]
                write_memory_byte -> 2149056108 [0% host]
                read_register_base -> 42791808162 [0% host]
                read_register_byte -> 77765418 [0% host]
                write_register_base -> 63041494692 [1% host]
                write_register_byte -> 3368185704 [0% host]
                utf8_decoding_base -> 3111779061 [0% host]
                utf8_decoding_byte -> 18661150656 [0% host]
                storage_write_base -> 449377152000 [10% host]
                storage_write_key_byte -> 14378504868 [0% host]
                storage_write_value_byte -> 9460654395 [0% host]
                storage_write_evicted_byte -> 9827895942 [0% host]
                storage_read_base -> 338141074500 [7% host]
                storage_read_key_byte -> 6066696468 [0% host]
                storage_read_value_byte -> 1105367985 [0% host]
                storage_remove_base -> 320838183000 [7% host]
                storage_remove_key_byte -> 5733057600 [0% host]
                storage_remove_ret_value_byte -> 2767573440 [0% host]
                touching_trie_node -> 2093254270380 [47% host]
                read_cached_trie_node -> 786600000000 [17% host]
                ------ Actions --------
                transfer -> 316495562500
                new_receipt -> 108059500000
                ------------------------------
                ,
            ),
        },
    },
    ExecutionOutcomeWithId {
        id: `HbFUbqwZTs3GKN4dKkqudC9oghEw5aiUvQSGhHvSKikH`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [],
            burnt_gas: 223182562500,
            tokens_burnt: 0,
            status: SuccessValue(``),
            metadata: V2(
                ------------------------------
                Action gas: 0
                ------ Host functions --------
                ------ Actions --------
                ------------------------------
                ,
            ),
        },
    },
    ExecutionOutcomeWithId {
        id: `8Vn5NCSNUiJuxYaRGDgEnA6SoMNw238psiX6R5ant2Gv`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [],
            burnt_gas: 223182562500,
            tokens_burnt: 0,
            status: SuccessValue(``),
            metadata: V2(
                ------------------------------
                Action gas: 0
                ------ Host functions --------
                ------ Actions --------
                ------------------------------
                ,
            ),
        },
    },
    ExecutionOutcomeWithId {
        id: `5PbCziYpPU31NC8DCFhKbp16aMN6MppunXVhAedb1pte`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [],
            burnt_gas: 223182562500,
            tokens_burnt: 0,
            status: SuccessValue(``),
            metadata: V2(
                ------------------------------
                Action gas: 0
                ------ Host functions --------
                ------ Actions --------
                ------------------------------
                ,
            ),
        },
    },
    ExecutionOutcomeWithId {
        id: `426RZSVGayRA93TMXSSchz4GZBwg1Uz4qeqWvYKY1nKM`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [],
            burnt_gas: 223182562500,
            tokens_burnt: 0,
            status: SuccessValue(``),
            metadata: V2(
                ------------------------------
                Action gas: 0
                ------ Host functions --------
                ------ Actions --------
                ------------------------------
                ,
            ),
        },
    },
    ExecutionOutcomeWithId {
        id: `EuWZXoTivpX89zNnaDKGX3MZsj8M8j6m9WmYkd3tvrf9`,
        outcome: ExecutionOutcome {
            logs: [],
            receipt_ids: [],
            burnt_gas: 223182562500,
            tokens_burnt: 0,
            status: SuccessValue(``),
            metadata: V2(
                ------------------------------
                Action gas: 0
                ------ Host functions --------
                ------ Actions --------
                ------------------------------
                ,
            ),
        },
    },
]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: StorageInconsistentState("Trie node missing")', tools/state-viewer/src/apply_chain_range.rs:291:86
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
## exit code 134
```

**Comment by kucharskim** [comment]
Got stuck at:
```
2022-07-21T10:05:59.906847Z  INFO stats: #70319624 Downloading blocks 100.00% (1326 left; at 70319624) 7 peers ⬇ 63.3 kB/s ⬆ 21.3 kB/s 0.00 bps 0 gas/s CPU: 4%, Mem: 1.09 GB
```

**Comment by bowenwang1996** [comment]
@nikurt do you mind comparing the state viewer outcome with what is on chain to see what went wrong? Thanks!

**Comment by telezhnaya** [comment]
Hey!
Please update to the latest version and feel free to re-open if it's still an issue for you
