### ISSUE TITLE
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Option::unwrap()` on a `None` value', chain/chain/src/chain.rs:2495:57

### ISSUE THREAD

**Issue by kucharskim** [near/nearcore#7817]
```
Oct 13 00:43:49 sandbox02 neard[1185538]: 102465065 4hkuea6ZsywcDTex3QTJSttFE18zzh9AeymoKoaWHcHD Processed in progress for 12461994ms orphan for 469ms  Chunks:(X✔✔✔))
Oct 13 00:43:53 sandbox02 neard[1185538]: thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Option::unwrap()` on a `None` value', chain/chain/src/chain.rs:2495:57
Oct 13 00:43:53 sandbox02 neard[1185538]: stack backtrace:
Oct 13 00:43:53 sandbox02 neard[1185538]:    0: rust_begin_unwind
Oct 13 00:43:53 sandbox02 neard[1185538]:              at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
Oct 13 00:43:53 sandbox02 neard[1185538]:    1: core::panicking::panic_fmt
Oct 13 00:43:53 sandbox02 neard[1185538]:              at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
Oct 13 00:43:53 sandbox02 neard[1185538]:    2: core::panicking::panic
Oct 13 00:43:53 sandbox02 neard[1185538]:              at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
Oct 13 00:43:53 sandbox02 neard[1185538]:    3: near_chain::chain::Chain::check_orphans
Oct 13 00:43:53 sandbox02 neard[1185538]:    4: near_chain::chain::Chain::postprocess_ready_blocks
Oct 13 00:43:53 sandbox02 neard[1185538]:    5: near_client::client_actor::ClientActor::try_process_unfinished_blocks
Oct 13 00:43:53 sandbox02 neard[1185538]:    6: near_client::client_actor::ClientActor::check_triggers
Oct 13 00:43:53 sandbox02 neard[1185538]:    7: <near_client::client_actor::ClientActor as actix::handler::Handler<near_network::types::NetworkClientMessages>>::handle
Oct 13 00:43:53 sandbox02 neard[1185538]:    8: <actix::address::envelope::SyncEnvelopeProxy<M> as actix::address::envelope::EnvelopeProxy<A>>::handle
Oct 13 00:43:53 sandbox02 neard[1185538]:    9: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
Oct 13 00:43:53 sandbox02 neard[1185538]:   10: tokio::runtime::task::raw::poll
Oct 13 00:43:53 sandbox02 neard[1185538]:   11: tokio::task::local::LocalSet::tick
Oct 13 00:43:53 sandbox02 neard[1185538]:   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Oct 13 00:43:53 sandbox02 neard[1185538]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Oct 13 00:43:53 sandbox02 systemd[1]: neard.service: Main process exited, code=killed, status=6/ABRT
```

**Comment by kucharskim** [comment]
This is from `testnet` machine.

```
$ /data/neard/neard --version
neard (release 1.30.0-rc.2) (build 1.30.0-rc.2) (rustc 1.63.0) (protocol 57) (db 31)
```

**Comment by kucharskim** [comment]
..and I cannot really take `status` page as it's constantly timing out:
``
mikolaj@sandbox02:~$ time curl -m120 -sSf localhost:3030/status | jq -r .
curl: (28) Operation timed out after 120001 milliseconds with 0 bytes received

real    2m0.013s
user    0m0.046s
sys     0m0.009s
```

I tried even longer timeouts and no luck.

**Comment by mzhangmzz** [comment]
@kucharskim There are a lot of bad blocks circulating in testnet now, the behavior of status page timing out is expected. We are working on resolving the issue. During this time, I think the best option for you is to just wait. If you really need to get a node started, you can try to use a243384f434d71f853287f4dc769d15fb12fdf3d from https://github.com/near/nearcore/commits/1.30.0-rpc-patch. That should help with your issues temporarily. We will release rc.4 soon

**Comment by kucharskim** [comment]
@mzhangmzz I'm aware. What I am reporting here is process panicked. That should not happen, no matter what is going on on the chain. This can be used as DDoS.

**Comment by mzhangmzz** [comment]
> @mzhangmzz I'm aware. What I am reporting here is process panicked. That should not happen, no matter what is going on on the chain. This can be used as DDoS.

Yes, definitely. We will look into the panic issue. Thank you very much for reporting!
