### ISSUE TITLE
RPC Near node crashes regularly.

### ISSUE THREAD

**Issue by elshan-eth** [near/nearcore#8478]
**Describe the bug**

RC node crashes regularly. Here is the last error. 
This is an RPC node in testnet with a custom trie_viewer_state_size_limit value (5_000_000_000).

```

2023-01-31 18:54:33 | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace. |  
-- | -- | --
  |   | 2023-01-31 18:54:33 | stack backtrace:    0: rust_begin_unwind              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5    1: core::panicking::panic_fmt              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14    2: core::result::unwrap_failed              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5    3: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll    4: tokio::runtime::task::raw::poll    5: tokio::task::local::LocalSet::tick    6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll |  
  |   | 2023-01-31 18:54:33 | thread 'actix-rt\|system:0\|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(DBNotFoundErr("epoch block: 9wbe5YBWX7CpdsG2rMQxQSV5idQyL2AiNBshBhJL2ePh"))', chain/client/src/client_actor.rs:270:47 |  
  |   | 2023-01-31 18:54:33 | 2023-01-31T14:54:33.446332Z ERROR client: Unwrap error: DB Not Found Error: epoch block: 9wbe5YBWX7CpdsG2rMQxQSV5idQyL2AiNBshBhJL2ePh |  
  |   | 2023-01-31 18:54:33 | 2023-01-31T14:54:33.084270Z  INFO db: Created a new RocksDB instance. num_instances=1 |  
  |   | 2023-01-31 18:54:33 | 2023-01-31T14:54:33.084257Z  INFO near: Opening an existing RocksDB database path=/data/data |  
  |   | 2023-01-31 18:54:33 | 2023-01-31T14:54:33.084216Z  INFO db: Dropped a RocksDB instance. num_instances=0 |  
  |   | 2023-01-31 18:54:33 | 2023-01-31T14:54:33.046433Z  INFO db: Created a new RocksDB instance. num_instances=1 |  
  |   | 2023-01-31 18:52:33 | 2023-01-31T14:52:33.384360Z  INFO neard: version="1.31.0-rc.2" build="1.31.0-rc.2-modified" latest_protocol=57 |  
  |   | 2023-01-31 18:52:12 | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace. |  
  |   | 2023-01-31 18:52:12 | stack backtrace:    0: rust_begin_unwind              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5    1: core::panicking::panic_fmt              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14    2: core::result::unwrap_failed              at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5    3: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll    4: tokio::runtime::task::raw::poll    5: tokio::task::local::LocalSet::tick    6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll |  
  |   | 2023-01-31 18:52:12 | thread 'actix-rt\|system:0\|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(DBNotFoundErr("epoch block: 9wbe5YBWX7CpdsG2rMQxQSV5idQyL2AiNBshBhJL2ePh"))', chain/client/src/client_actor.rs:270:47 |  
  |   | 2023-01-31 18:52:12 | 2023-01-31T14:52:12.999154Z ERROR client: Unwrap error: DB Not Found Error: epoch block: 9wbe5YBWX7CpdsG2rMQxQSV5idQyL2AiNBshBhJL2ePh
```

**Comment by akhi3030** [comment]
@nikurt: looks like something the node team could help triage.

**Comment by nikurt** [comment]
Looks like DB corruption: https://near-nodes.io/troubleshooting/common-errors
Please consider downloading a snapshot: https://near-nodes.io/intro/node-data-snapshots
