### ISSUE TITLE
PrepareError (Deserialization) occurred when call contract function on mainnet (same call works on testnet)

### ISSUE THREAD

**Issue by pvolnov** [near/nearcore#9339]
I try to run the method on a smart contract on mainnet and get an error. At the same time, the same contract successfully works on testnet 

Contracts (same code hash)
- https://explorer.testnet.near.org/accounts/dev-1689978891109-21148171224736
- https://explorer.near.org/accounts/giveaway.mydev.near

Calls
- Transaction on testnet (success): https://explorer.testnet.near.org/transactions/FfkhL8MCWVoxjRHaBUNHxFuhMpD67YG4oDA94QENVwFi
- Transaction on mainnet (error): https://explorer.near.org/transactions/H4j1fh2BBMB4U5HGNoLyFM2FHaVUsFWiSGM9Wxt8QTwh

all tests pass.

dependencies:
```
near-sdk = "4.1.1"
near-contract-standards = "4.1.1"
serde = "^1.0.36"
log = "0.4.16"
```

error:
```

Receipts: 8YDbcHrTV1CDYzhDP2ZsKvsP6BkANzKyFKacvyTGczx, GRXCQW9SykeA87fPvXvns6QpyHVxoBS3nK2qbSoaNKJ2
        Failure [giveaway.mydev.near]: Error: Error happened while deserializing the module
ServerTransactionError: Error happened while deserializing the module
    at Object.parseResultError (/opt/homebrew/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/rpc_errors.js:31:29)
    at Account.signAndSendTransactionV2 (/opt/homebrew/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:160:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async scheduleFunctionCall (/opt/homebrew/lib/node_modules/near-cli/commands/call.js:57:38)
    at async Object.handler (/opt/homebrew/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'Deserialization',
  context: undefined,
  index: 0,
  transaction_outcome: {
    block_hash: '5s6soBQiDanFQkdo4eVdVgRsmjZ37aSPVCANvtpxeab3',
    id: 'H4j1fh2BBMB4U5HGNoLyFM2FHaVUsFWiSGM9Wxt8QTwh',
    outcome: {
      executor_id: 'mydev.near',
      gas_burnt: 2428081987248,
      logs: [],
      metadata: [Object],
      receipt_ids: [Array],
      status: [Object],
      tokens_burnt: '242808198724800000000'
    },
    proof: [ [Object], [Object], [Object] ]
  }
}
```

Any ideas what could be the problem?

**Comment by nagisa** [comment]
Without investigating this very much, could it be https://github.com/near/nearcore/issues/9143?

**Comment by nagisa** [comment]
I’m going to close this now that the protocol version upgrade has occurred and the suspected issue is resolved.

Please re-open if the issue persists. Thank you.
