### ISSUE TITLE
Analyze background node fetching performance

### ISSUE THREAD

**Issue by Longarithm** [near/nearcore#9375]
* End-to-end (locust) test to replicate slowness (currently possible with many hacks, it has to be a more replicable setup)
	* Need some communication with Node team
	* Test will be used to verify the improvement

**Comment by Longarithm** [comment]
Current progress:
* After couple days of learning, could launch mirroring for the only existing setup on height XXX. My branch with disabled background fetching works ([Grafana](https://nearinc.grafana.net/d/jHbiNgSnz/mocknet?orgId=1&var-chain_id=All&var-node_id=.%2Alogunov-new-mirror.%2A&var-account_id=All&from=1690974691887&to=1690977922495))
* With enabled background fetching nodes crash with error, I will investigate it
```
thread 'actix-rt|system:0|arbiter:2' panicked at 'Cannot update flat head to GTrgwbrks8pjEwd6vdWvKUBkZZPVEFDyRM9cJuCGt4Qj: StorageInternalError("delta does not exist for block GTrgwbrks8pjEwd6vdWvKUBkZZPVEFDyRM9cJuCGt4Qj")', chain/chain/src/chain.rs:2294:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: near_chain::chain::Chain::update_flat_storage_for_block
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Longarithm** [comment]
I was giving updates in the [Zulip thread](https://near.zulipchat.com/#narrow/stream/313099-pagoda.2Fstorage/topic/background.20node.20fetching/near/381550952) during the last week. Current summary:

### Too small State latency

* I was testing the idea on the mirrored mainnet traffic since height 74020501. Though [peak BP time reaches 10s](https://nearinc.grafana.net/d/jHbiNgSnz/mocknet?orgId=1&var-chain_id=All&var-node_id=mocknet-mainnet-74020501-logunov-meta-f2bm&var-account_id=All&from=1691699954119&to=1691747094184) many times for current protocol, [avg State latency is below 100 us](https://nearinc.grafana.net/d/db67cd58-fac4-437a-acdb-1ebfc71f41ca/rocksdb-performance?orgId=1&var-node_id=mocknet-mainnet-74020501-logunov-meta-f2bm&var-column=State&from=1691700063059&to=1691746317107). More granular debug metrics show that [Main Thread state reads don't reach 500 ms](https://nearinc.grafana.net/d/ef3e39f9-e049-4f7f-8fd2-ef35645148db/storage-debug?orgId=1&var-node_id=mocknet-mainnet-74020501-logunov-meta-f2bm&var-shard_id=3&from=1691699729621&to=1691746682671) which is way above 10s again. 
But **my target is 600 us** which was reached during the incidents. Consistent 6x lower latency means that storage is not a bottleneck for that test, thus background fetching improvement was not visible.

* I tried the same experiment on the locust workload. And it has the same issue - **during high load** [State latency is too smal](https://nearinc.grafana.net/d/db67cd58-fac4-437a-acdb-1ebfc71f41ca/rocksdb-performance?orgId=1&var-node_id=mocknet-mainnet-74020501-logunov-new-mirror-rbvh&var-column=State&from=1691676720787&to=1691679179000).

### Finally, an improvement

However, using the same debug metrics we can clearly see that idea improves time spent on Main Thread State reads: [without fetching](https://nearinc.grafana.net/d/ef3e39f9-e049-4f7f-8fd2-ef35645148db/storage-debug?orgId=1&var-node_id=mocknet-mainnet-74020501-logunov-meta-f2bm&var-shard_id=3&from=1691699729621&to=1691746682671), [with fetching](https://nearinc.grafana.net/d/ef3e39f9-e049-4f7f-8fd2-ef35645148db/storage-debug?orgId=1&var-node_id=mocknet-mainnet-74020501-logunov-mirror2-xzgq&var-shard_id=3&from=1691699729621&to=1691746682671). But there is no confirmation that it resolves the incident, yeah.

**Comment by Longarithm** [comment]
Won't needed because of https://github.com/near/near-one-project-tracking/issues/5
