### ISSUE TITLE
Found an active validator that is not whitelisted

### ISSUE THREAD

**Issue by 0xdefacto** [near/nearcore#9392]
**Describe the bug**
I have found an active validator whose account ID is `stocked.near`. What confused me is that it is not a whitelisted validator.

```bash
$ NODE_ENV=mainnet near view lockup-whitelist.near is_whitelisted --args '{"staking_pool_account_id": "stocked.near"}'
View call: lockup-whitelist.near.is_whitelisted({"staking_pool_account_id": "stocked.near"})
false
```
And it even doesn't have code.

```bash
$ NODE_ENV=mainnet near view stocked.near get_reward_fee_fraction
View call: stocked.near.get_reward_fee_fraction()
An error occured
Error: Querying [object Object] failed: wasm execution failed with error: CompilationError(CodeDoesNotExist { account_id: AccountId("stocked.near") }).
{
  "block_hash": "4nFAxvH9eLSC3pbNCBPX7RmPVRFgYSGnkXVGgtgZAvTC",
  "block_height": 98048088,
  "error": "wasm execution failed with error: CompilationError(CodeDoesNotExist { account_id: AccountId(\"stocked.near\") })",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:123:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Account.viewFunction (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/usr/local/lib/node_modules/near-cli/index.js:103:48)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9)
TypedError: Querying [object Object] failed: wasm execution failed with error: CompilationError(CodeDoesNotExist { account_id: AccountId("stocked.near") }).
{
  "block_hash": "4nFAxvH9eLSC3pbNCBPX7RmPVRFgYSGnkXVGgtgZAvTC",
  "block_height": 98048088,
  "error": "wasm execution failed with error: CompilationError(CodeDoesNotExist { account_id: AccountId(\"stocked.near\") })",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:123:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Account.viewFunction (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/usr/local/lib/node_modules/near-cli/index.js:103:48)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'UntypedError',
  context: undefined
}
```

What I want to ask is if it is normal to have a non-whitelisted validator in the active validator set. Is there something wrong? Or if it is by-design, what's this validator used for?

**To Reproduce**
```bash
$ NODE_ENV=mainnet near repl
> await near.connection.provider.validators(97948295);
```
97948295 is the end block height of epoch 2039. You will find `stocked.near` in the output current_validators.

**Expected behavior**
A non-whitelisted validator should not be selected as an active validator.

**Version (please complete the following information):**
- mainnet

**Additional context**

**Comment by walnut-the-cat** [comment]
Not an active validator anymore. Also it doesn't seem to be a staking pool, but an independent validator
