### ISSUE TITLE
Loadtest script does not work

### ISSUE THREAD

**Issue by staffik** [near/nearcore#9637]
**Bug**
I encountered an error while trying to run loadtest script on localnet:
> Traceback (most recent call last):
>   File "/Users/user/near/nearcore/pytest/tests/loadtest/setup.py", line 29, in <module>
>     shard_key = key.Key.from_json_file(
>   File "/Users/user/near/nearcore/pytest/lib/key.py", line 37, in from_json_file
>     with open(filename) as rd:
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/.near/localnet/node0/shard0_key.json'

**To Reproduce**
Run:
```
export PYTHONPATH=~/near/nearcore/pytest/lib 
python3 pytest/tests/loadtest/setup.py --home ~/.near/localnet/node0 --num_accounts=2
python3 pytest/tests/loadtest/loadtest.py --home ~/.near/localnet/node0 --num_accounts=2 --num_requests=100 --contract_type=compute
```

**Version**
Commit: d7ad5265ce4f20c87abd823a9cf7f1035e163cb8
Rust version: `rustc 1.72.0 (5680fa18f 2023-08-23)`
`Localnet`

**Comment by wacban** [comment]
The issue here is that the setup or the loadtest depend on a feature that was removed. 

It used to work by using the --fixed-shard argument when setting it. The fixed shards feature was adding a few accounts called shardX and putting them in different shards. 

In order to fix this issue we will need to create some test accounts in a different way. I believe we should have access to the private keys of either the top level account "near" or to the accounts created for the validators in the network "node0", "node1", ... . We can use those to create the test accounts like a.near, k.near, z.near (ideally spread evenly across alphabet and shards). 

On a sidenote I believe the instructions on how to use those scripts is stored in a private wiki page. We should move that to github.
