### ISSUE TITLE
Missing, malformed or inaccessible config file(s) cause code panics

### ISSUE THREAD

**Issue by gmilescu** [near/nearcore#9950]
<p> <em><b>Describe the bug</b></em> </p>

<p>Running `neard` commands with an absent configuration file will cause `neard` invocations to panic, rather than to print out an error message and terminate regularly.</p>

<p>For example:</p>

<p>    1\.  ./target/release/neard view_state peers<br/>
 Nov 26 17:56:58.036 INFO neard: Version: trunk, Build: crates-0.10.0-64-gdcab6f416-modified, Latest Protocol: 49<br/>
 thread 'main' panicked at 'Could not open config file: `~/.near/config.json`', nearcore/src/config.rs:469:33<br/>
 stack backtrace:<br/>
 0: rust_begin_unwind<br/>
 at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5<br/>
 1: core::panicking::panic_fmt<br/>
 at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14<br/>
 2: nearcore::config::Config::from_<a href="file::" class="external-link" rel="nofollow noreferrer">file::</a>(<a href="file::" class="external-link" rel="nofollow noreferrer">file::</a>)`closure`<br/>
 3: nearcore::config::Config::from_file<br/>
 4: nearcore::config::load_config_without_genesis_records<br/>
 5: nearcore::config::load_config<br/>
 6: state_viewer::cli::StateViewerSubCommand::run<br/>
 7: neard::cli::NeardCmd::parse_and_run<br/>
 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.<br/>
 ```</p>

<p>    Touching the config file causes a different, more opaque panic:</p>

<ol>
	<li>mkdir ~/.near && touch ~/.near/config.json && ./target/release/neard view_state peers Nov 26 18:00:07.619 INFO neard: Version: trunk, Build: crates-0.10.0-64-gdcab6f416-modified, Latest Protocol: 49 thread 'main' panicked at 'Failed to deserialize config: Error("EOF while parsing a value", line: 1, column: 0)', nearcore/src/config.rs:502:39 stack backtrace: 0: rust_begin_unwind at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5 1: core::panicking::panic_fmt at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14 2: core::result::unwrap_failed at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/result.rs:1617:5 3: nearcore::config::Config::from_file 4: nearcore::config::load_config_without_genesis_records 5: nearcore::config::load_config 6: state_viewer::cli::StateViewerSubCommand::run 7: neard::cli::NeardCmd::parse_and_run note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.</li>
</ol>


<p>If the config file exists, but cannot be opened or read from for other reasons, the panics like those above will be presented.</p>

<p> <em><b>Expected behavior</b></em> </p>

<p>`neard` should print an error message rather than raise a panic. These are user errors, not inherent mistakes in the codebase. Additionally, my belief is that the error messages should attempt to retain the causal chain so that it is possible to present not just `failed to deserialize config` but also `could not obtain config from "~/.near/config.json"`.</p>

<p> <em><b>Version (please complete the following information):</b></em> </p>

<ul>
	<li>dcab6f416</li>
	<li>1.56</li>
	<li>local</li>
</ul>

<i>[ND-78] created by None</i>

[ND-78]: https://pagodaplatform.atlassian.net/browse/ND-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by gmilescu** [comment]
Closing as duplicate of #5485.
